### ISSUE TITLE
Failed token creation breaks PyViCare

### ISSUE THREAD

**Issue by drgrandios** [openviess/PyViCare#10]
When `getNewToken()` fails (e.g. due to network errors), the function returns (implicitly) `None`.

This eventually leads to `self.oauth` becoming `None` - and all functions using it will fail with an Exception (because they are trying to access `post()` or `get()` on the `None` object).

I'm using PyViCare as the backend for the [ViCare Home Assistant component](https://github.com/oischinger/ha_vicare/) and unfortunately have to restart Home Assistant each time this error occurs (e.g. when the Viessmann servers rejected connection due to whatever reason...).

**Comment by somm15** [comment]
Hum, that's a good one.
If there is a network error, I believe I should raise a network exception and break at PyVicare level.
The home assistant component should decide what to do (e.g. create a new PyVicare object).
I want to avoid endless loops of bad calls.
@oischinger Do you have any opinion on this?

**Comment by somm15** [comment]
@drgrandios Could you copy/paste your logs here to check which exception is raised please?

**Comment by oischinger** [comment]
I'm not sure if the HA component can really handle that situation in a good way.

What it could probably do is check if the token is valid before every call. If it's not valid it'll try to call getNewToken() before making any further calls/until the token is valid.

Unfortunately I cannot make any changes during the next few days since I'm traveling, but I'll check it asap.

**Comment by drgrandios** [comment]
> @drgrandios Could you copy/paste your logs here to check which exception is raised please?

I'm not sure this will help, it just shows the `AttributeError` due to accesses on the `None` object:
![screenshot_ha](https://user-images.githubusercontent.com/28082191/54332283-c2efc480-461d-11e9-9676-88299adeaac9.png)

I guess the easiest solution would be to just throw an exception on failed token creation/renewal (should be enough to raise it at the end of `__getNewToken()` ). In my opinion the HA component shouldn't try additional token actions and just fail (once). The next sensor/climate update will just try again. Though it would be nice if direct user interaction (e.g. set temperature manually in the HA web UI) could give a response that the requested action failed.
