### ISSUE TITLE
Publish PyPi

### ISSUE THREAD

**Issue by crazyfx1** [openviess/PyViCare#108]
Hi @woehrl01 

Is there anything missing now for pushing to PyPi? I would like to release the current version as 1.0.0.

Thanks

**Comment by woehrl01** [comment]
Not from my side. Feel free to publish.
 I'm just missing access to provide the required secret, so er can publish via a GitHub release (and GitHub Action). But I don't mind for the current situation.

**Comment by crazyfx1** [comment]
I have actually never published something to PyPi. Would you mind doing that? :)

**Comment by woehrl01** [comment]
Sure, no worries. I just published 1.0.0
