### ISSUE TITLE
Move OneTime charge capabilities to GenericDevice

### ISSUE THREAD

**Issue by kruemel746** [openviess/PyViCare#110]
In order to trigger the hot water heating, the function "getHotWater" was available in the old API. Currently this does not seem to work. In the Viessmann App the feature works properly.
With my gas heater I get the errror:
AttributeError: 'GazBoiler' object has no attribute 'getHotWater'

Thanks a lot for your fantastic work!

**Comment by adorobis** [comment]
Which Viessmann heater are you using?

**Comment by kruemel746** [comment]
I´m using a Vitodens-333-F connected via Vitoconnect 100.

**Comment by adorobis** [comment]
@kruemel746 We don't have data for your system. Would you be able to [test the API](https://github.com/somm15/PyViCare#api-usage-in-postman) for your system with Postman? If yes you should execute this API:
`https://api.viessmann.com/iot/v1/equipment/installations/<your_installation_id>/gateways/<your_gateway_id>/devices/0/features` and submit the output json in new pull request here. 
And regarding the `getHotWater`: is this the same as onetimecharge function that some devices have?

**Comment by kruemel746** [comment]
Yes, its the onetimecharge! I will try to send you the output.

**Comment by prior-philip** [comment]
I added that to my PyViCareHeatPump.py manually and it works fine but I suspect its same for Gaz heaters and others...

    @handleNotSupported
    def deactivateOneTimeCharge(self):
        return self.service.setProperty("heating.dhw.oneTimeCharge","deactivate","{}")

    @handleNotSupported
    def activateOneTimeCharge(self):
        return self.service.setProperty("heating.dhw.oneTimeCharge","activate","{}")

**Comment by adorobis** [comment]
> I suspect its same for Gaz heaters and others

From what I can see it is available in Vitodens 300W and 333W but not in 200W and 222W. So in general should be available for gas heaters and heatpumps but depends on specific model.

**Comment by kruemel746** [comment]
Thanks a lot! I added it manually to PyViCareGazBoiler.py and it also works well for my gas heater!

**Comment by woehrl01** [comment]
@kruemel746 I added the feature via PR #62 a while ago with `getOneTimeCharge`, `activateOneTimeCharge` and `deactivateOneTimeCharge`. I'm curious that you were unable to find it on your implementation. Which version did you use?

**Comment by prior-philip** [comment]
> @kruemel746 I added the feature via PR #62 a while ago with `getOneTimeCharge`, `activateOneTimeCharge` and `deactivateOneTimeCharge`. I'm curious that you were unable to find it on your implementation. Which version did you use?

BTW: Why is that statement part of PyViCareGazBoiler.py? As above commands are pretty generic I would them expect to be with PyViCareDevice.py. Heatpump uses them as well..

**Comment by woehrl01** [comment]
@prior-philip I added it only to GazBoiler as I simply just have that device 😄, and thus the only response back then for testing. Moving that feature to Device, is a good idea.

**Comment by prior-philip** [comment]
Great, thanks. One more question...
What needs to happen to get PyViCare officially upreved in order to make recent changes available with pip3 ?

**Comment by woehrl01** [comment]
@prior-philip Which problem are you facing with pip3? To keep things sorted, please open another issue for that topic, thanks.

**Comment by kruemel746** [comment]
Am an absolute Python beginner. Didn't find it in the readme and looked in the wrong place in the source code. :-)

**Comment by woehrl01** [comment]
@kruemel746 We are all a beginner somewhere 🐱.  Thank you for bringing this up to our attention!
