### ISSUE TITLE
Investigate HA OAuth2 facilities

### ISSUE THREAD

**Issue by oischinger** [openviess/PyViCare#115]
Home Assistant has built-in support for integrations that offer account linking using the OAuth2 authorization framework. To be able to leverage this, you will need to structure your Python API library in a way that allows Home Assistant to be responsible for refreshing tokens.

https://developers.home-assistant.io/docs/config_entries_config_flow_handler/#configuration-via-oauth2

To be honest I have no idea about all this OAuth stuff. Does someone here have enough knowledge to judge if this is feasible?
Would certainly be a nice feature.

**Comment by woehrl01** [comment]
This shouldn't be such a big issue, we just need to extract/refactor the authentication. See: https://developers.home-assistant.io/docs/api_lib_auth

I can get my hands dirty over the weekend.
