### ISSUE TITLE
Suggestion for using local cache with a ttl to reduce ratelimit issue

### ISSUE THREAD

**Issue by jborup** [openviess/PyViCare#129]
First thanks for maintaining the PyViCare package - awesome job!

After the change of the Viessmann API and the ratelimit I was wondering if it would not make sense to introduce a local caching for feature GETs? 
I am using home assistant and I would like to increase the update frequence but if I do so at the current implementation that would break the ratelimit. However for the pulling of values they are all represented under the https://developer.viessmann.com/en/doc/device-features-mw-iot/v1 call anyway? If I get that right then setting an optional "ttl" of for instance 60 seconds, it would be possible to get the status of the device much more often rather than doing the individual feature GET requests. Behind the scene then the individual get-calls could look in the cache first before doing a real API call if needed be, and cache it locally. Could be configured similar to how the token is saved.

Any reflections would be highly appreciated on this?

**Comment by crazyfx1** [comment]
I'm a bit confused why we get so many requests for that feature, although this is already implemented for a long time.

- PyViCare supports caching by passing the cacheDuration as parameter.
- The ViCare integration in HomeAssistant has a default cache duration of 60 seconds
- 60 seconds cache is the lowest you can go with the daily limit of 1450 requests

**Comment by woehrl01** [comment]
Hi @jborup thank you for your idea. 

Actually, this is already implemented and can be controlled via `setCacheDuration` at the `PyViCare` class. Starting from 2.x this is set to 60 seconds per default. Which lets you stay inside the current API rate limit.

At earlier versions, this has to be manually set to more than 0, to be enabled. (outside of Home Assistant, where the default is 60)

edit: looks like I was to slow @crazyfx1 😄

**Comment by woehrl01** [comment]
@jborup You mentioned that you would like to increase the update frequency in Home Assistant. Which benefit do you see in this, when all the calls are hitting the cached values?

**Comment by jborup** [comment]
@woehrl01 @crazyfx1 thanks for the quick response, and agree all seems to be cached.

After looking at the code I can only say I jumped to conclusions, it is all cached and looks good! I will have to check what issues I might have on the home assistant side.

PS! Since I had to dig deeper anyway I created the test for Vitodens300W along with the test, you should have it as a simple PR for now. Rather puzzled why Viessmann has not ensured essential values are available at the moment for 300Ws (such as burner info), I wrote to Viessmann in case others also wonders... just FYI.
