### ISSUE TITLE
When will pyViCare be updated in PyLib

### ISSUE THREAD

**Issue by prior-philip** [openviess/PyViCare#131]
typo in "/usr/local/lib/python3.9/dist-packages/PyViCare/PyViCareService.py" line 48

Error raised:
dump() missing 1 required positional argument: 'fp' in python json

Change
 post_data = data if isinstance(data, str) else json.dump(data)
to
 post_data = data if isinstance(data, str) else json.dumps(data)

**Comment by woehrl01** [comment]
Thanks @prior-philip for reporting this. I'm just pushing a fix. Not sure what you mean with the title of the issue, though.

**Comment by prior-philip** [comment]
sry. Title might be pre-filled by browser. I thought I entered a more meaningful text
