### ISSUE TITLE
Security issue & PyViCare might not work in the future 

### ISSUE THREAD

**Issue by cheinz71** [openviess/PyViCare#142]
Hi there,
I have a question to the security layer of this library.
As callback URL, the following has to be configured: "**vicare://oauth-callback/everest**"
This is not a valid schema, obviously intended by the author.
As a result, The Authorization Code workflow fails by calling the redirect URI to transmit the Auth Code. 
The PyViCare library expects the resulting exception in file "PyViCareServiceV2.py", function "__getNewToken" by the following code:
```
 try:
            header = {'Content-Type': 'application/x-www-form-urlencoded'}
            response = requests.post(authorization_url, headers=header,auth=(username,password))
            logger.warning("Received an HTML answer from the server during auth, this is not normal:")
            logger.debug(response.content)
        except requests.exceptions.InvalidSchema as e:
            #capture the error, which contains the code the authorization code and put this in to codestring
            codestring = "{0}".format(str(e.args[0])).encode("utf-8")
```
In my point of view, this contradicts the security of OAUTH2 because an unique redirect URL is part of the security concept.
Probably not a big deal because the attacker must also know the credentials and the client ID. 
But if Viessmann changes the API Registration form and allows only valid redirect URI schemes in future, PyViCare won't work anymore.

Just my thoughts....

Best regards,
Christian

**Comment by woehrl01** [comment]
Hi @cheinz71

Thank you very much for bringing this up. These are absolutely valid concerns. This should definitely be addressed.

**Comment by woehrl01** [comment]
I just modified the logic so that it is not relying on the invalid schema exception any more. As mentioned in the PR it's not addressing all off your concerns as we currently are not relying on using the browser for the credential workflow. For Home assistant, this will be part of that integration. For another a browser only integration, an additional OAuth Manager needs to be implemented.

**Comment by woehrl01** [comment]
@cheinz71 I just added a browser-based OAuth flow, which address the issues you described here. You need to add `localhost:51125` as your redirect uri. Currently, the port is not configurable.
