### ISSUE TITLE
Add additional properties for heat pumps

### ISSUE THREAD

**Issue by crazyfx1** [openviess/PyViCare#16]
Add additional properties from the viessmann API for heat pumps:
- Compressor starts
- Compressor hours

Add additional property for all heating systems:
- Dhw pump status

**Comment by somm15** [comment]
Hi. Do you have the exact path for the properties ? 
I don't have an heat pump so I don't see them in the API

**Comment by crazyfx1** [comment]
Yes, you can see the paths in the PR I created.
