### ISSUE TITLE
Add Solar properties

### ISSUE THREAD

**Issue by williwacker** [openviess/PyViCare#161]
Please add
- getSolarStorageTemperature
- getSolarPowerProduction
to the PyVicareDevice.py code

**Comment by woehrl01** [comment]
@williwacker Thank you for providing the changes. As we don't have any test response yet, which has these values provided, could you please also add a test response? [How to do it as easy as possible is written in the readme](https://github.com/somm15/PyViCare#more-different-devices-for-test-cases-needed).

**Comment by williwacker** [comment]
Added test output viessmann.data as the routine dump_secure is not found in the code

**Comment by woehrl01** [comment]
@williwacker I found your fork and used your changes to pull into the repo. Thanks for providing the test output. The missing method for dumping the output is available in the latest version 2.5.2. 

I also just published 2.6 which includes the new solar sensors.
