### ISSUE TITLE
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.dhw.temperature

### ISSUE THREAD

**Issue by sweh** [openviess/PyViCare#167]
Hi there,

since 2.6 release I get the following error with my Vitodens W200:

```
t.getDomesticHotWaterConfiguredTemperature()
*** PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.dhw.temperature
```

All other api calls like `setDomesticHotWaterTemperature` are working.

Any ideas?

**Comment by woehrl01** [comment]
Hi @sweh 

It looks like that this property is not supported on your device. Did you receive a valid response in the past? What was the previous version where the call worked successfully?

**Comment by woehrl01** [comment]
Reopen as we still need a fix for setting of the temperature (see: https://github.com/oischinger/ha_vicare/issues/47)
