### ISSUE TITLE
Ask viessmann for the doc

### ISSUE THREAD

**Issue by smrt28** [openviess/PyViCare#18]
Hi,
have you ever tried to ask Viessmann tech support for the doc?

**Comment by somm15** [comment]
Actually, I didn't. That's a fair point.

**Comment by somm15** [comment]
I did request the doc a week ago. So far, no answer.

**Comment by crazyfx1** [comment]
Things are getting in motion on viessmann side. I guess you all received the viessmann survey because they realized people are fetching data from their API. Maybe we get a full documentation soon ;)

**Comment by michelde** [comment]
I also got this e-mail and stated in the survey that I would like to get the full documentation. But I was also wondering as there were two questions, where they asked if I'm willing to pay for the API..

**Comment by smrt28** [comment]
I would suggest everybody who read this issue, haras viessmann and ask for the API by yourself.

**Comment by smrt28** [comment]
btw, I asked them for the API and I got a response, I should use vitogate for $600🙈 I was arguing little bit and you should do the same.

The responsive contacts are: technical-uk@viessmann.com, customer-care@viessmann.com,
vicare-service@viessmann.com

**Comment by crazyfx1** [comment]
> I also got this e-mail and stated in the survey that I would like to get the full documentation. But I was also wondering as there were two questions, where they asked if I'm willing to pay for the API..

Well I just answered "No". I already paid for the heating system and the vitoconnect so they can have all data from my heating system.

**Comment by ddokupil** [comment]
Viessmann should know that community around their product would do much more profit for them than any marketing campaign in industry press.

**Comment by somm15** [comment]
I finally received my survey as well :-)
I got a mixed feeling. The mail has a positive tone but they talk a lot about paid services. 
From my point of view, it's easy. 
In an IOT world, you have an open API and if possible, it should be possible to access an API directly on the device without using the cloud. 

Actually, we should give that feedback, make the ViCare device accessible directly, we would not query the cloud anymore...

**Comment by vandenberghev** [comment]
The cloud data is a treasure trove for them, I don’t believe they will ever allow/encourage official direct access to the device.

You can already access the device directy BTW, the same way the gateway does: using an IR adapter.

**Comment by oischinger** [comment]
I also asked for local APIs. Asking doesn't hurt and I strongly believe that local APIs are an important step towards reliable home automation.
In the end I hope the don't monetize their APIs completely. After all it's my data.

**Comment by somm15** [comment]
I got an SMA inverter and a Zehnder system, both have local "API".
Even my vacuum cleaner can be addressed directly...

**Comment by jennes** [comment]
> The cloud data is a treasure trove for them, I don’t believe they will ever allow/encourage official direct access to the device. You can already access the device directy BTW, the same way the gateway does: using an IR adapter.

In my case this wouldn't be beneficial: As long as I provide data to them, they provide me with a five year warranty. But exactly because I pay them already with my data, I'm absolutely not willing to pay twice.

**Comment by jennes** [comment]
> I finally received my survey as well :-)
> I got a mixed feeling. The mail has a positive tone but they talk a lot about paid services.
> From my point of view, it's easy.
> In an IOT world, you have an open API and if possible, it should be possible to access an API directly on the device without using the cloud.
> 
> Actually, we should give that feedback, make the ViCare device accessible directly, we would not query the cloud anymore...

But as they also collect these data, one could also ask them to give the stored data to you based on the GPDR regulations. I did that already once a while ago and I think it is time to do it again, soon. :smiley:
