### ISSUE TITLE
Home Assistant ViCare integration

### ISSUE THREAD

**Issue by to-masz** [openviess/PyViCare#183]
Hi! Is there any ongoing work to update the Home Assistant Viessmann ViCare integration (https://www.home-assistant.io/integrations/vicare/) to use PyViCare 2.x? Or would be there anyone interested to start/join such an effort? cc @oischinger 

It looks like in HA the 1.0.0 adoption happened (https://github.com/home-assistant/core/pull/53281) - mainly because of the old api shutdown. I can see several things are not working properly there. 

Moreover, it looks like there is no possibility to integrate more than one circuit and this is something people would like to have (https://community.home-assistant.io/t/viessmann-vicare-integration-multiple-circuits-possible/150441).

From https://analytics.home-assistant.io/#integrations we can see that The Viessmann ViCare integration is used by `94 (0.1 %)` active installations. It can be a case that some people do not share stats from HA, but still that number does not sound like a reasonable time investment. That is why I would like to figure out what could be the value proposition of ViCare in HA 🤔 And that is why I post here in the PyViCare - what are the use cases for this library? Do you use it to integrate with other automations? 

I can think only about few things not possible to achieve with native ViCare application:
* Manage the heating system based on your family location 
* Try to include the humidity of the room as the dependency in the target temperature
* Try to dynamically modify the heating curve based on additional factors (solar radiation, wind speed, ...)
* Persist statistics and other data in time series db (i.e. energy consumption, circuit's current supply temperature, ...) - think of Grafana Dashboard with the data about your installation
* Get data from ViCare Smart Climate (as VItoconnect is the Zigbee Gateway for them)

Probably I am interested only in the last two - so I am thinking whether it makes sense to fix/develop current integration in Home Assistant or rather build a simple data fetcher.

**Comment by woehrl01** [comment]
Hi @to-masz 

The developing work for the Home Assistant integration is tracked in the ha_vicare repo. The adoption for the latest update of this lib is in the following PR: https://github.com/oischinger/ha_vicare/pull/43

In the current HA integration, multiple circuits are already possible, but need to be manually configured. 

I'm not certain if I understood your question?

**Comment by to-masz** [comment]
Ok, thanks. Then, I believe I know where to contribute. I was not aware the ha integration development happens in the @oischinger's repository 😉  

> In the current HA integration, multiple circuits are already possible, but need to be manually configured.

You mean the current or the one in-progress in oischinger/ha_vicare#43? Any chance to get a tip how to make it?

**Comment by woehrl01** [comment]
It's in the already existing official HA integration. In your `configuration.yml` set the `circuit` to your circuit id. (see https://www.home-assistant.io/integrations/vicare/#circuit)

The current integration, in development, has auto-detection in place.
