### ISSUE TITLE
Schedule entries ending with 24:00 fail parsing with datetime.strptime

### ISSUE THREAD

**Issue by sskrlj** [openviess/PyViCare#186]
My schedule entries frequently finish at midnight and Viessmann decided to write this as `"end": "24:00"`, causing `datetime.strptime` in `endTime = datetime.strptime(s["end"], '%H:%M').time()` to complain with `ValueError: time data '24:00' does not match format '%H:%M'`.

**Comment by woehrl01** [comment]
Thanks, for the report. This should definitely be fixed.

**Comment by sskrlj** [comment]
For the purpose of fixing failing `getDomesticHotWaterActiveMode` in
`         for s in schedule[current_day]:
             startTime = datetime.strptime(s["start"], '%H:%M').time()
             endTime = datetime.strptime(s["end"], '%H:%M').time()
             if startTime <= currentTime and currentTime <= endTime:
                 if s["mode"] == VICARE_DHW_TEMP2:  # temp-2 overrides all other modes
                     return s["mode"]
                 else:
                     mode = s["mode"]
         return mode`
I think endTime should go to 00:00 with a day (24h) added to it. But then `time` type won't suffice and some additional attention needs to be paid to either bringing startTime to current date or stripping down current date to `1900-01-01`. Or 
 special comparison logic implemented for 24:00 case.
