### ISSUE TITLE
getBurnerActive no longer works

### ISSUE THREAD

**Issue by SPITZGITHUB** [openviess/PyViCare#194]
# #Hello,

since weeks I get the status of the burner via Python and "getBurnerActive" as false or true. Since yesterday this request occurs an error: **_"PyViCareNotSupportedFeatureError: heating.burner"_**. I run a FuelCell and here are all variables I can got:

_device = vicare.devices[0]
t = device.asFuelCell()
circuit = t.circuits[0] #select heating circuit
Komma =";"
ZW = str(t.getDomesticHotWaterStorageTemperature())
Wert = ZW + Komma
ZW = str(t.getOutsideTemperature())
Wert = Wert + ZW + Komma
ZW = str(circuit.getSupplyTemperature())
Wert = Wert + ZW + Komma
ZW = str(t.getReturnTemperature())
Wert = Wert + ZW + Komma
ZW = str(t.getDomesticHotWaterDesiredTemperature())
Wert = Wert + ZW + Komma
ZW = str(t.getDomesticHotWaterConfiguredTemperature())
Wert = Wert + ZW + Komma
ZW = str(t.getBurnerActive())
Wert = Wert + ZW + Komma
ZW = str(t.getOneTimeCharge())
Wert = Wert + ZW + Komma
ZW = str(circuit.getDesiredTemperatureForProgram("reduced"))
Wert = Wert + ZW + Komma
ZW = str(circuit.getDesiredTemperatureForProgram("normal"))
Wert = Wert + ZW + Komma
ZW = str(circuit.getDesiredTemperatureForProgram("comfort"))
Wert = Wert + ZW + Komma
ZW = circuit.getActiveProgram()
Wert = Wert + ZW + Komma
print(Wert)_

Has someone an idea why the request doesn't work anymore? Are there more values I can get from the fuelcell?

Thanks for your help

**Comment by woehrl01** [comment]
Hi @SPITZGITHUB,

Which version of the library do you use?

In order to help us troubleshoot the issue, please create a dump of the response json as described in the Readme and upload as attachment to this issue.

Thanks!

**Comment by TvoDebug** [comment]
Same here using PyVicare-2.8.1

Don't get any value anymore since yesterday for:

h = device.asHeatPump()
g = device.asGazBoiler()

circuit = h.circuits[0]
circuit_gaz = g.getCircuit(0)
circuit_hp = h.getCircuit(0)

g.getBurnerActive())
circuit_gaz.getBurnerHours()
circuit_gaz.getBurnerStarts()
circuit_gaz.getBurnerModulation()
circuit_hp.getCompressorActive()
circuit_hp.getCompressorHours()
circuit_hp.getCompressorStarts()

Thanks for helping. Don't know how tp get log files.

**Comment by kruemel746** [comment]
Same here. I attach the dump-file!

[dump.json.txt](https://github.com/somm15/PyViCare/files/7257553/dump.json.txt)

**Comment by woehrl01** [comment]
@kruemel746 thanks for the file. What is the version and code you are using?

**Comment by SPITZGITHUB** [comment]
The version: Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.
IPython 7.22.0 -- An enhanced Interactive Python.

Attached the dumpfil
[dump_heating.txt](https://github.com/somm15/PyViCare/files/7258551/dump_heating.txt)
e

**Comment by woehrl01** [comment]
@SPITZGITHUB thank you for the result I'll have a look later. As the issue is closed, where you able to resolve the issue on your end?

**Comment by SPITZGITHUB** [comment]
I do not understand what you mean? Issue closed mean not solved the problem, but anyway closed? I can´t solve the problem on my side!

**Comment by TvoDebug** [comment]
@woehrl01 I was also confused that topic was closed without a solution :D 
For my understanding closed is meaning solved or not needed anymore. 
I think nobody will work on closed topics? 
Please correct me If I'm wrong.

**Comment by kruemel746** [comment]
Version:
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)] on win32

PyVicare-2.8.1

Thanks for all your help!

**Comment by TvoDebug** [comment]
Maybe also a hint from Api documentation:
![Screenshot_20210930-160517_Chrome](https://user-images.githubusercontent.com/63579386/135470721-c8d2e3b6-2f1b-408e-a54b-67e217758f48.jpg)
I'm Not Sure If Interation is covered by current pyvicare lib

**Comment by woehrl01** [comment]
I just debugged the issue, it looks like that the property has changed in the response instead of `heating.burner` it's now `heating.burners.0` 

Thanks for your test responses. Can I have your permission to use your responses to update my test suite? @SPITZGITHUB  and @kruemel746

**Comment by woehrl01** [comment]
For now, I used my response. I resolved the issue and published version `2.9.0` with the fix. Please notify the breaking change, see #195 for the new API usage.

If the issue still persists, please let us know. Thanks.

**Comment by TvoDebug** [comment]
Please consider also burner.statistics.N and for Heatpump heating.compressor.N and Heating.compressor.N.statistics

Thank you for fixing and quick help

**Comment by woehrl01** [comment]
@TvoDebug yep, I'll have a look for these in a dedicated PR to keep things clean.

**Comment by woehrl01** [comment]
@TvoDebug I just verified that the mentioned properties are already correctly populated via the API. I just published an updated verison `2.9.1` to keep the naming consistent across burner and compressor. (see #196 ). It's now `getActive` for both.

**Comment by kruemel746** [comment]
@woehrl01 yes, of course. let me know if i can help in any way! Unfortunately I am a total beginner :-)

All the "device"-features seem to work now.

The only "circuit"-function not working since the last api-update is getCurrentDesiredTemperature().
error-message: 
site-packages\PyViCare\PyViCareUtils.py", line 45, in feature_flag_wrapper return wrapper(*args, **kwargs)
site-packages\PyViCare\PyViCareUtils.py", line 40, in wrapper raise PyViCareNotSupportedFeatureError(func.__name__)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: getCurrentDesiredTemperature

should i open another issue?

thanks again!

**Comment by Friedi1970** [comment]
I really have no clue about python :( but anyway my HA created a binary sensor ‘ binary_sensor.vicare_burner_active’ but it’s status is claimed with exclamation mark as ‘not available’ and I don’t know why.
Is there a hint to get this working?

**Comment by oischinger** [comment]
check if you have a sensor binary_sensor.vicare_burner_active_2
There was a breaking change in the latest Home Assistant release for binary sensors.

In that case delete the inactive sensor and binary_sensor.vicare_burner_active_2 will become binary_sensor.vicare_burner_active on next restart

**Comment by Friedi1970** [comment]
I have no binary_sensor.vicare_burner_active_2 but the binary_sensor.vicare_burner_active.
But this one is marked as not available :-(

**Comment by oischinger** [comment]
Are you using the custom integration or the official vicare integration in Home assistant. Make sure that both are up 2 date.
There was a recent Bugfix that could apply to your problem

**Comment by Friedi1970** [comment]
Hm. I use the official one. Ho can I update the official integration?
HA is up to date (latest versions).

**Comment by oischinger** [comment]
That should be fine then. You are using the latest code.

Can you check the logs and filter for Vicare?

**Comment by Friedi1970** [comment]
Wow, that’s weird. I just did a reboot and suddenly there are a lot more entities with ‘_2’ at the end.
And now the binary_sensor.vicare_burner_active_2 works.

The bad thing: all the old entities are dead while the _2-ones are working. What do you suggest to do?

**Comment by oischinger** [comment]
Please remove all the dead entities and restart HA.
Then everything will behave as expected again.

This is a breaking change that was also mentioned in the latest HA Release notes.
Sorry for the confusion

**Comment by Friedi1970** [comment]
> Please remove all the dead entities and restart HA. Then everything will behave as expected again.

Unfortunately now the *_2 entities are active. Anyway, it works now 👍 

> This is a breaking change that was also mentioned in the latest HA Release notes. Sorry for the confusion

No worries. "Wo gehobelt wird, fallen Späne."

WELL DONE!

**Comment by cagnulein** [comment]
same here. Removed the the dead entities and now it's working again. Thanks
