### ISSUE TITLE
Question: Burner Active state missing for you as well

### ISSUE THREAD

**Issue by williwacker** [openviess/PyViCare#202]
Hi,
Since starting of this week I no longer get the BurnerActive state from the API. I have installed the latest version but no change.
Does anybody else is having the same problem? Or is this a setup problem?
Thanks

**Comment by crazyfx1** [comment]
Did you check #194 ?

**Comment by williwacker** [comment]
Thanks,
I have checked this.
But I see that it is not related to the code that extracts the individual values. Fact is that the heating feature is not providing the burner component:
`[({"apiVersion": 1, "isEnabled": true, "isReady": true, "gatewayId": "################", "feature": "heating", "uri": "https://api.viessmann.com/iot/v1/equipment/installations/#######/gateways/################/devices/0/features/heating", "deviceId": "0", "timestamp": "2021-10-03T10:10:34.769Z", "properties": {}, "commands": {}, "components": ["boiler", "circuits", "device", "dhw", "sensors", "operating", "solar"]}, )]`
What I also see is that my burner is listed as `VScotHO1_72` model which doesn't seem to match to my Vitocrossal burner.
