### ISSUE TITLE
setDomesticHotWaterTemperature feature throwing error

### ISSUE THREAD

**Issue by prior-philip** [openviess/PyViCare#208]
Getting error when setting "setDomesticHotWaterTemperature" and "setDomesticHotWaterTemperature2" with integer value.

`File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 154, in setDomesticHotWaterTemperature
    return self.service.setProperty("heating.dhw.temperature.main", "setTargetTemperature", {'temperature': temperature})
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 29, in setProperty
    response = super().setProperty(property_name, action, data)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 52, in setProperty
    return self.oauth_manager.post(url, post_data)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 91, in post
    self.__handle_command_error(response)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareAbstractOAuthManager.py", line 67, in __handle_command_error
    raise PyViCareCommandError(response)
PyViCare.PyViCareUtils.PyViCareCommandError: (PyViCareCommandError(...), 'Command failed with status code 422. Reason given was: VALIDATION_ERROR')`

Is this a known issue? Did the API change?

**Comment by woehrl01** [comment]
This can have three reasons: 
1. The command is not supported on your side
2. More likely. A value is sent which is outside the allowed range.
3. Not verified, but could also be an issue: You are passing in the temperature as a string instead of an integer (try using `int(value)` as the argument.

**Comment by prior-philip** [comment]
Yepp (3) was it. The MQTT value that my script got was treated as str. Transforming to int solved it. 

Some values are sting, some are int. But all commands are processed within same routine, probably not just in my scripts..
I kindly request to add int(value) in PyViCareDevice for values expected as integer.

**Comment by woehrl01** [comment]
Thanks for confirming nummero three. I'll add that cast into the library.

**Comment by prior-philip** [comment]
Solved by changing numeric value to integer

**Comment by woehrl01** [comment]
I just published `2.11.1` with this fix. @prior-philip

**Comment by prior-philip** [comment]
Thanks, really appreciate it.
