### ISSUE TITLE
Need some clarification

### ISSUE THREAD

**Issue by MichiFr** [openviess/PyViCare#209]
Sorry for posting a such a help request here rather than on discord. Discord is unfortunately too complicated for me and far away from user friendly!

My Vitodens 200W supports `heating.dhw.oneTimeCharge`, at least this reveals a Postman GET-request. There are many properties my device supports but almost all fail and result in an exception because PyViCare expects some further properties when requesting a state or a value.

For example 
      `    @handleNotSupported
    def getOneTimeCharge(self):
return self.service.getProperty("heating.dhw.oneTimeCharge")["properties"]["active"]["value"]`

While the property `heating.dhw.oneTimeCharge` is available this is not true for the `active `attribute. Just because one time charge is currently inactive, the call to the method results in a exception instead of simply return a false.

I may be wrong, may be Viessmann changed too many things in their API, but the previous version of PyViCare, with old API(?) , was somehow more modest. Many of the requests did not result in a hard exception. At least this is my experience.

Or maybe I totally misunderstood how the new PyViCare library now works?

**Comment by woehrl01** [comment]
@MichiFr. Please have a look if `isEnabled` and `isReady` are both `true` on the entry. Even though a few is available in the api it's still can be that it's not working.

Even though the library has been refactored and updated on the usage level, it still uses the old access methods. If the method does not return a value, it simply is not supported on your device, even though it has worked in the past. There is sadly nothing we can do here from the maintainer perspective of this library.

Please also see my comments on #203 which things have changed in the API side of Viessmann.

**Comment by MichiFr** [comment]
Hi and thanks for your reply!

Is this the JSON below that should be found by method `getOneTimeCharge`?

```
},
            "components": [],
            "apiVersion": 1,
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxxx/gateways/xxxx/devices/0/features/heating.dhw.oneTimeCharge",
            "gatewayId": "xxxxxxxxxx",
            "feature": "heating.dhw.oneTimeCharge",
            "timestamp": "2021-10-05T01:01:40.457Z",
            "isEnabled": true,
            "isReady": true,
            "deviceId": "0"
        },
      {
            "properties": {},
            "commands": {},
            "components": [],
```

IMO `isEnabled` and `isReady` is true, nevertheless the call to method `getOneTimeCharge` fails.

I understand that now missing "features" of the current Viessmann API may cause some issues, but so far I always re-checked with the Postman data and got the impression, that one or more properties are still supported by my device , however, PyViCare fails because it expects more attributes for finding the correct state in its coding. 

Regarding my example: one time charge is currently not running so it is my understanding that `properties` above is empty. Although I would expect some more attributes, similar to those one.
```
{
            "properties": {
                "active": {
                    "type": "boolean",
                    "value": false
                }
            },
```
PyCiCare however expects `"heating.dhw.oneTimeCharge")["properties"]["active"]["value"]` to determine the state. 
So why does the method `getOneTimeCharge` not return false in this case instead of raising an exception?

**Comment by crazyfx1** [comment]
It seems like you didn't provide the whole part of "oneTimeCharge".

```JSON
        {
            "properties": {
                "active": {
                    "value": false,
                    "type": "boolean"
                }
            },
            "commands": {
                "activate": {
                    "uri": "https://api.viessmann.com/iot/v1/equipment/installations/154905/gateways/7571381818533105/devices/0/features/heating.dhw.oneTimeCharge/commands/activate",
                    "name": "activate",
                    "isExecutable": true,
                    "params": {}
                },
                "deactivate": {
                    "uri": "https://api.viessmann.com/iot/v1/equipment/installations/154905/gateways/7571381818533105/devices/0/features/heating.dhw.oneTimeCharge/commands/deactivate",
                    "name": "deactivate",
                    "isExecutable": false,
                    "params": {}
                }
            },
            "components": [],
            "apiVersion": 1,
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxxx/devices/0/features/heating.dhw.oneTimeCharge",
            "gatewayId": "xxxx",
            "feature": "heating.dhw.oneTimeCharge",
            "timestamp": "2021-10-04T00:53:56.331Z",
            "isEnabled": true,
            "isReady": true,
            "deviceId": "0"
        },
```

You can see on top the properties object with the value property.

**Comment by crazyfx1** [comment]
It seems like you didn't provide the whole part of "oneTimeCharge".

```JSON
        {
            "properties": {
                "active": {
                    "value": false,
                    "type": "boolean"
                }
            },
            "commands": {
                "activate": {
                    "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxxx/devices/0/features/heating.dhw.oneTimeCharge/commands/activate",
                    "name": "activate",
                    "isExecutable": true,
                    "params": {}
                },
                "deactivate": {
                    "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxx/devices/0/features/heating.dhw.oneTimeCharge/commands/deactivate",
                    "name": "deactivate",
                    "isExecutable": false,
                    "params": {}
                }
            },
            "components": [],
            "apiVersion": 1,
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxxx/devices/0/features/heating.dhw.oneTimeCharge",
            "gatewayId": "xxxx",
            "feature": "heating.dhw.oneTimeCharge",
            "timestamp": "2021-10-04T00:53:56.331Z",
            "isEnabled": true,
            "isReady": true,
            "deviceId": "0"
        },
```

You can see on top the properties object with the value property.

**Comment by woehrl01** [comment]
Hi @MichiFr , if you look at all the existing test results, `["properties"]["active"]["value"]` is set to `false` if it's currently not active. Could you please send us a test output for both cases:

1. When you have one time charge disabled.
2. When you have enabled it via the official ViCare App.

If we have a testcase that his is actually a behaviour of your device I'm happy to add the edge case to the library. Please also have a look if `commands` is populated also on your response.

**Comment by MichiFr** [comment]
So here is the complete one time charge output. 

The JSON is really hard to read, you know, because I would expect the appropriate feature `heating.dhw.oneTimeCharge` on top and the state below. It seems it is somehow distracted. 

So my data looks similar to yours @crazyfx1 

```
{
            "properties": {
                "active": {
                    "value": false,
                    "type": "boolean"
                }
            },
            "commands": {
                "activate": {
                    "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxx/devices/0/features/heating.dhw.oneTimeCharge/commands/activate",
                    "name": "activate",
                    "isExecutable": true,
                    "params": {}
                },
                "deactivate": {
                    "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxx/devices/0/features/heating.dhw.oneTimeCharge/commands/deactivate",
                    "name": "deactivate",
                    "isExecutable": false,
                    "params": {}
                }
            },
            "components": [],
            "apiVersion": 1,
            "uri": "https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxx/devices/0/features/heating.dhw.oneTimeCharge",
            "gatewayId": "xxxx",
            "feature": "heating.dhw.oneTimeCharge",
            "timestamp": "2021-10-05T01:01:40.457Z",
            "isEnabled": true,
            "isReady": true,
            "deviceId": "0"
        },
```
@woehrl01 Yes, this is what I would expect too and as far as I can see from the output above, it **is** set to false. 

_I know how to program for many decades now and I know about logical conditions and values very well, however, web services and JSON formatted answers are new to me. So please excuse if I post wrong parts of JSON outputs and as mentioned above, it's very hard to read which part of the JSON are linked or not._

**Comment by woehrl01** [comment]
@MichiFr No worries, we are here to help. 

The output looks like it should be, strange that the error happens for you. Could you please verify that you use the latest version of the lib by running `pip show PyViCare` ?

**Comment by MichiFr** [comment]
Sure, just noticed version 2.11 was release 3 days before.

Name: PyViCare
Version: 2.10.0
Summary: Library to communicate with the Viessmann ViCare API
Home-page: https://github.com/somm15/PyViCare
Author: Simon Gillet
Author-email: mail+pyvicare@gillet.ninja
License: UNKNOWN
Location: c:\users\michael\appdata\local\programs\python\python38\lib\site-packages
Requires: pkce, requests-oauthlib
Required-by:

Added my dump here if someone would like to have a deeper look:
[dump.zip](https://github.com/somm15/PyViCare/files/7296209/dump.zip)

Thanks!

**Comment by woehrl01** [comment]
this looks all good. Can you please share how you call and use the library?

**Comment by MichiFr** [comment]
@woehrl01 I guess my wrong usage of the various class methods is what causes my issues: I've added some helper classes that should help me when calling PyViCare methods, performing some more actions including pushing the data into Grafana.

I just noticed that when setting up a basic example, based on the dump code here on the first page of the project, I get correct values back!

I too, noticed that I've to use the `devices` attribute, similar to coding below, to get the appropriate methods working:

```
import sys
import os
from PyViCare.PyViCare import PyViCare
from vi_consts import VI_PASSWORD, VI_CLIENTID, VI_USER, CACHE_TIMEOUT, TOKEN_FILE, BUCKET, DEVICE

client_id = os.getenv("PYVICARE_CLIENT_ID", VI_CLIENTID)
email = os.getenv("PYVICARE_EMAIL", VI_USER)
password = os.getenv("PYVICARE_PASSWORD", VI_PASSWORD)

vicare = PyViCare()
vicare.initWithCredentials(email, password, client_id, "token_testing.save")
dev = vicare.devices[0].asAutoDetectDevice()
otc = dev.getOneTimeCharge( )
print(otc)
```

This returns exactly `false`. Which is the current state of the device. So this basically means, I've to rethink about how to call the PyViCare methods with my helper class.

At the moment it's a bit hard to understand how devices, burners and similar have to be used when calling any class method.

So, sorry for confusion in above case. It seems all is well so far and the mistake was simply my lack of understanding how to use the library :-(

**Comment by woehrl01** [comment]
Glad to hear that you found the root cause of the problem. If you have any suggestions on improving the readme and/or documentation of the library to make things more clear, I would be more than happy to hear them. All the best for your refactoring. I'll close the issue. You are welcome to reopen.
