### ISSUE TITLE
PyViCareInvalidCredentialsError

### ISSUE THREAD

**Issue by jcplu** [openviess/PyViCare#215]
Hello,
I updated the file with my client_id, email and password.
Client_id created with Name= PyViCare and URi= vicare://oauth-callback/everest
I have a PyViCareInvalidCredentialsError because there is no Location in my response.headers.
How to fix that ?

**Comment by woehrl01** [comment]
Hi @jcplu ,

the missing `Location` header is an indication of invalid credentials, as this is basically the required redirection after a successful login of the OAuth flow.

Let's see how we can troubleshoot his. 
* How do you use the library? (Integration HA, custom code, etc?)
* Which version do you use of the library?
* What is the debug output? As if the lib fails due to missing `Location` header [an output is made.](https://github.com/somm15/PyViCare/blob/master/PyViCare/PyViCareOAuthManager.py#L70)
* Do you have a proxy in place, which could drop the header?
* If you use the library in a custom made solution, does the login work if you use `pyvicare.initWithBrowserOAuth()` (you need access to a browser on the device to make this work)

**Comment by jcplu** [comment]
Hi @woehrl01,
- custom code in python
- I installed it with pip , version 2.12.0
-  where can I find the log ? I printed the response

`
<Response [200]>
{'Date': 'Sat, 09 Oct 2021 07:40:14 GMT', 'Server': 'Apache', 'Set-Cookie': 'NPSession=b11b14ac1515CQnOa...XXXXXX...I6WDRGCk7s7vcCEpRwGQAL7N; Path=/; Secure; HttpOnly, iam_pers_sess=ffffffffaf1c0b04455...XXXXXX...e445a4a42378b;expires=Sat, 09-Oct-2021 08:10:17 GMT;path=/;secure;httponly', 'Cache-Control': 'no-store, no-cache, must-revalidate, private', 'Expires': 'Thu, 1 Jan 1970 00:00:00 GMT', 'Content-Type': 'text/html;charset=utf-8', 'Keep-Alive': 'timeout=30, max=200', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Strict-Transport-Security': 'max-age=63072000'}
`
- no proxy
- login works in a browser ; can I use special characters in password ?

- vicare.initWithBrowserOAuth(client_id, "token.save")  # no token file present
{"error":"Invalid redirection URI."}

**Comment by woehrl01** [comment]
Thank you for the hint with the special characters, I dived into the `auth` library we use from python, as it looks like that the following snipped is not encoding character the way as the Viessmann API is expecting them 

```
#File: /usr/local/lib/python3.8/dist-packages/requests/auth.py:65

authstr = 'Basic ' + to_native_string(
        b64encode(b':'.join((username, password))).strip()
    )
```

Can you tell me what kind of special characters you use so that I can create a testcase on my end, to see how we can fix this from the library perspective?

**Comment by woehrl01** [comment]
I forgot: to make the login via browser work (from the lib) you need to add `http://localhost:51125` as an additional valid URL at the Viessmann portal.

**Comment by jcplu** [comment]
special characters : + - \\
also I noticed that "IoT User" is written IoT+User ? is it the same as IoT%20User ?

**Comment by jcplu** [comment]
with localhost added > Success. You can close this browser window now.

**Comment by woehrl01** [comment]
Yes, `+` and `%20` are basically the "same" encoding for a whitespace.

I'll have a look at the special chars, as `:` is a character which separated the user form the password in a basic authentication. 

If you use a `\`, do you escape it properly, in a python string? Just that we are confident that this is not the issue?

**Comment by jcplu** [comment]
Oups ! working, tnx

**Comment by woehrl01** [comment]
Awesome, enjoy. Happy coding!

**Comment by jcplu** [comment]
Where can I find the log if needed ?

**Comment by woehrl01** [comment]
In a Home Assistant environment, it's automatically wired up.

If you have a custom code you have to configure the logger:

```
logger = logging.getLogger('ViCare')
logger.addHandler(logging.StreamHandler(sys.stdout))
```

of couse you can wire up the logger (e.g. file) however you want

**Comment by jcplu** [comment]
How can I get the full list of the commands available for my Vitoconnect ?

**Comment by woehrl01** [comment]
Currently they only way to find out which commands are available, [is to dump the feature response](https://github.com/somm15/PyViCare#more-different-devices-for-test-cases-needed), and search through the resulting JSON, for all the available commands.

**Comment by jcplu** [comment]
In Vicare app, I have access to the programs : reduced and normal.
When I print with PyViCare, I have ['active', 'comfort', 'eco', 'external', 'holiday', 'normal', 'reduced', 'standby'].
Is it possible to use all the programs ?

**Comment by woehrl01** [comment]
As there are different responses across the test suite, I expect yes. But the the only way to find out is by simply testing.

Keep in mind standby equals to of, and holiday requires sending an end date which is currently not implemented.

The api validates the request so you will receive an error if it's not working.

**Comment by jcplu** [comment]
Ok, tnx for all. I have the dump.json if needed (vitoconnect 100 opto1).
Last question for this day, which interior temperature sensor do you advice me to add in my installation ?
The goal is to get inside and outiside temperatures in real time to update with optimal settings.

**Comment by woehrl01** [comment]
Personally, I use Home Assistant as my central control solution. I have Homematic Thermostats at my radiators and also a Homematic Temperature Sensor in each room linked to the radiators. I prefer not interacting with the overall heating temperature of the house all too much, by having the correct curve and shift, and have it all setup on a general schedule. The only automatic on/off switching is enabling of hot water based on presence. I turn the heating device based on calendar, external temperature, weather forecast of the day and temperature delta of the living room. I also use the valve level of some radiators as an input if "heat is required".
