### ISSUE TITLE
Vitodens 100w - expose consumption data

### ISSUE THREAD

**Issue by hnykda** [openviess/PyViCare#217]
Hi,

I noticed that my Gas Boiler Vitodens 100w just recently got an update in ViCare android app and I can see daily/weekly/monthly statistics. But when I try e.g. `t.getGasConsumptionDomesticHotWaterToday`, I get `PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.gas.consumption.dhw`. In the `device.get_raw_json()` I can see `heating.power.consumption` being enabled, but have no idea what that means. Is there any chance how to get it from API as well? Would be cool to have these statistics in my HA installation.

**Comment by woehrl01** [comment]
Hi, 

You just mentioned that `heating.power.consumption` is in the `get_raw_json` response. The method you use is the gas consumption. Does `getPowerConsumptionDays()` work for you?

**Comment by hnykda** [comment]
Nope, I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dan/.cache/pypoetry/virtualenvs/vicare-5rfMLF8Q-py3.9/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 45, in feature_flag_wrapper
    return wrapper(*args, **kwargs)
  File "/home/dan/.cache/pypoetry/virtualenvs/vicare-5rfMLF8Q-py3.9/lib/python3.9/site-packages/PyViCare/PyViCareUtils.py", line 38, in wrapper
    return func(*args, **kwargs)
  File "/home/dan/.cache/pypoetry/virtualenvs/vicare-5rfMLF8Q-py3.9/lib/python3.9/site-packages/PyViCare/PyViCareGazBoiler.py", line 110, in getPowerConsumptionDays
    return self.service.getProperty("heating.power.consumption.total")["properties"]["day"]["value"]
  File "/home/dan/.cache/pypoetry/virtualenvs/vicare-5rfMLF8Q-py3.9/lib/python3.9/site-packages/PyViCare/PyViCareCachedService.py", line 26, in getProperty
    return readFeature(entities, property_name)
  File "/home/dan/.cache/pypoetry/virtualenvs/vicare-5rfMLF8Q-py3.9/lib/python3.9/site-packages/PyViCare/PyViCareService.py", line 17, in readFeature
    raise PyViCareNotSupportedFeatureError(property_name)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.power.consumption.total
```

**Comment by hnykda** [comment]
![image](https://user-images.githubusercontent.com/2741256/136689704-320914b4-6359-4036-9156-f553b72c23e8.png)
this is in the app

**Comment by hnykda** [comment]
```
>>> t.service.getProperty("heating.power.consumption")
{'properties': {}, 'commands': {}, 'components': [], 'apiVersion': 1, 'uri': 'https://api.viessmann.com/iot/v1/equipment/installations/xxx/gateways/xxxx/devices/0/features/heating.power.consumption', 'gatewayId': 'xxx', 'feature': 'heating.power.consumption', 'timestamp': '2021-10-08T22:19:14.764Z', 'isEnabled': True, 'isReady': True, 'deviceId': '0'}
```

**Comment by hnykda** [comment]
The app needs to get it from somewhere, right? Can I sniff it maybe? :grin:

**Comment by crazyfx1** [comment]
The app uses a different API and we can’t use that anymore. If the consumption data is missing in your response, you can only write to viessmann to include it for your system.

**Comment by hnykda** [comment]
thank you, will do.

**Comment by hnykda** [comment]
Any particular contact I should use?

**Comment by crazyfx1** [comment]
There is an email address on the Viessmann developer portal.

**Comment by numanx11** [comment]
Hi there, viessmann added API support for gas and power consumption.

https://www.viessmann-community.com/t5/The-Viessmann-API/Pulling-consumption-statistics-from-API/m-p/193620/emcs_t/S2h8ZW1haWx8bWVudGlvbl9zdWJzY3JpcHRpb258S1ZHRDZaTDlCRFdMVkd8MTkzNjIwfEFUX01FTlRJT05TfGhL#M343

https://developer.viessmann.com/en/doc/changelog

**Comment by woehrl01** [comment]
@numanx11 The mentioned endpoints have been implemented already. If they don't return values for you, it's likely not supported or enabled on your device. In either case, you need to reach out to Viessmann support directly.
