### ISSUE TITLE
Batching requests to the Viessmann servers

### ISSUE THREAD

**Issue by oischinger** [openviess/PyViCare#22]
I was wondering if it would be possible to avoid doing too many requests at the same time. Currently we have a situation that the Home Assistant integration gets a lot of data via the API which result in lots of GET requests on the API at the same time.
With today's outage of the viessmann servers this results in lots of exceptions but it's also not nice to the servers.

Could we change/extend the API to select the data we're interested in and then requesting it with a single GET?

Would be interesting to get our thoughts on this.

**Comment by crazyfx1** [comment]
Seems like they limited the amount of API requests now to 1450 per day.

```JSON
{
    "statusCode": 429,
    "errorType": "RATE_LIMIT_EXCEEDED",
    "message": "API calls rate limit has been exceeded. Please wait until your limit will renew.",
    "extendedPayload": {
        "name": "ViCare day limit",
        "requestCountLimit": 1450,
     }
}
```

**Comment by crazyfx1** [comment]
I would suggest a method which executes the request and caches the JSON result. All other get methods use the cached JSON. 
In home-assistant the implementation is quite easy then: On each update, execute the request first and use the methods like before. And make sure we use a scan_interval of at least 60 seconds.

**Comment by adorobis** [comment]
So we now have some data on the limits published on the forum [LINK](https://www.viessmann-community.com/t5/Experten-fragen/Betreff-Q-amp-A-Viessmann-API/qaq-p/127732/comment-id/117660#M117660):
```
Currently, we have two limits active:
120 calls for a time window of 10 minutes
1450 calls for a time window of 24 hours
We see these limitations reasonable, also based on your great explanation concerning cloud based services. So thank you for that!
Also, we decided against HATEOAS as it is deprecated and will sooner or later be switched off.
```
Any chance to update the integration to respect those limits?

**Comment by oischinger** [comment]
I created a PR to Home assistant which sets the scan_interval of the ViCare integration to 15 minutes. It seems like we're on the safe side with that.
It should make it into HA 0.107.

But we could reduce the scan_interval quite a bit if we work on this.

**Comment by crazyfx1** [comment]
The fix works for now, thanks.

Now we can discuss on how to implement the batching. Are there any plans so far @somm15 ?

**Comment by somm15** [comment]
I think this has been solved.
