### ISSUE TITLE
Is there a way to control supply temperature (directly or indirectly)?

### ISSUE THREAD

**Issue by ddokupil** [openviess/PyViCare#23]
I wanted to try PID routines to control room temperature - in order to optimize gas consumption - they say that lower temperature is more effective...
Anyway, I'd need to be able to set supply temperature for that.
I can't directly set supply temperature, neither can I set heating curve through API.
Hypothetically, knowing curve and outside temp I could change program temperature to maybe achieve what I want.
Maybe anyone here knows better way to do that? Anyone tried playing around with PID to control room temperature?

**Comment by crazyfx1** [comment]
Viessmann added the feature of setting the heating curve to the ViCare app. I would guess it's also possible to it via the API now.

**Comment by adorobis** [comment]
You might want to look at this project: https://github.com/openv/openv it is connecting directly to the heater via optolink cable and publishes REST API. Maybe we could use it to integrate with HA as well?
Also I would be interested to see what you can achieve with PID, hope you'll share your results :)

**Comment by michelde** [comment]
@adorobis I think this would be a new / different implementation as this project is to get the data with the Vitoconnect module. Using the project you mentioned requires a different hardware (optolink cable).  There is already a project in python to read the data using the optolink cable [PyVito](https://github.com/olivimo/pyvito) This could be used as a starting point to make a HA integration or custom component.

**Comment by adorobis** [comment]
@michelde Yes, I understand that. I'm responding to question from @ddokupil who is trying to implement a PID controller for the viessmann device. Controlling it as PID via cloud service I believe does not make sense, more direct and frequent calls to the device would be required (which is problematic over the cloud API as we know). But correct me if I'm wrong. And thanks for the PyVito reference - is it as complete as the openv seems to be?

**Comment by somm15** [comment]
@michelde PyVito looks cool. OpenV appears to be complex and mainly documented in German. If PyVito is usable, I would probably use it rather than this library. Less cloud is always better.
Did you try it?

**Comment by somm15** [comment]
By the way, did you ever notice that the port "56747/tcp" is opened on the vitoconnect?
