### ISSUE TITLE
Heating curve calculation

### ISSUE THREAD

**Issue by idstein** [openviess/PyViCare#238]
Try to fully utilise PyVicare in my custom home assistant fork I run into an issue with regards to heating curve calculation on heat pumps (my scenario is a Vitocal 200-S with DHW tank AND buffer tank).

Looking into the current implementation it fully complies with the definition for Viessmann gas burner. The correct implementation can be extracted from Vitoguide.

All values are clipped to min and max flow temperature ("heating.circuits.X.temperature.levels" > min / max constraint) for each circuit.

```
# Given targetTemperature, shift, slope
alpha = outside - targetTemperature
# gas burner and if device has roles "type:heatpump", "type:E3"
flowTemperature = targetTemperature + shift - slope * alpha * (1.4347 + 2.1E-2 * alpha + 247.9E-6 * (alpha * alpha))
# heatpump has roles "type:heatpump" and with single circuit
flowTemperature = targetTemperature + shift - slope * alpha * (1.148987 + 2.1E-2 * alpha + 247.9E-6 * (alpha * alpha)) + 5
```

**Comment by woehrl01** [comment]
Thank you @idstein for the hint. 

This requires the extraction of the roles, which can also be used for the "auto" device type detection.

**Comment by woehrl01** [comment]
@idstein I just finished a PR (#239) which adds the behaviour you described. You are welcome to have a look and comment if I have missed something. Thanks!

**Comment by idstein** [comment]
The PR looks correct to me! Thx a lot for the quick fix.
