### ISSUE TITLE
water temp error

### ISSUE THREAD

**Issue by lenny76** [openviess/PyViCare#24]
If I set the temperature from the app Vicare with different settings like in the photo attached,
I receive always the "normal" temp instead of the "temp2" value

![photo_2020-02-12_12-24-22](https://user-images.githubusercontent.com/3609634/74330795-9e065300-4d92-11ea-9cc2-e9bef18edf40.jpg)

I'm showing this issue in home assistant

min_temp: 10
max_temp: 60
current_temperature: 46
**temperature: 45**
target_temp_high: null
target_temp_low: null
friendly_name: ViCare Water
supported_features: 1

**Comment by crazyfx1** [comment]
I have checked the viessmann API and it seems like there is no indication which dhw mode / temperature currently is active.
