### ISSUE TITLE
PyViCareNotSupportedFeatureError: heating.burners

### ISSUE THREAD

**Issue by SBAABS** [openviess/PyViCare#243]
Hey!

Since a few days I have an error out of the blue.
Before this error, everything was running fine. I already took attention regarding issue #194 and #195.

I receive an error message: _readFeature raise PyViCareNotSupportedFeatureError(property_name) PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.burners_

I've installed the latest version of PyViCare and run the simplest code and the same problem occur.
Does anyone have an idea what’s going on? I am out of ideas.
Pulling a JSON dump was possible.

This is the code:
          import sys
          import logging
          from PyViCare.PyViCare import PyViCare
          
          client_id = "myID"
          email = "myMail"
          password = "myPW"
          
          vicare = PyViCare()
          vicare.initWithCredentials(email, password, client_id, "token.save")
          device = vicare.devices[0]
          print(device.getModel())
          print("Online" if device.isOnline() else "Offline")
          
          t = device.asAutoDetectDevice()
          print(t.getDomesticHotWaterConfiguredTemperature())
          
          circuit = t.circuits[0] #select heating circuit
          print(circuit.getActiveMode())
          
          burner = t.burners[0] #select burner
          print(burner.getActive())

The result is as follows:
          E3_Vitodens_300_0419
          Online
          45
          dhwAndHeating
          Traceback (most recent call last):
            File "c:\Users\ChoSba\Desktop\PyViCare-master\Fehlersuche.py", line 21, in <module>
              burner = t.burners[0] #select burner
            File "c:\Users\ChoSba\Desktop\PyViCare-master\PyViCare\PyViCareGazBoiler.py", line 11, in burners
              return list([self.getBurner(x) for x in self.getAvailableBurners()])
            File "c:\Users\ChoSba\Desktop\PyViCare-master\PyViCare\PyViCareUtils.py", line 45, in feature_flag_wrapper
              return wrapper(*args, **kwargs)
            File "c:\Users\ChoSba\Desktop\PyViCare-master\PyViCare\PyViCareUtils.py", line 38, in wrapper
              return func(*args, **kwargs)
            File "c:\Users\ChoSba\Desktop\PyViCare-master\PyViCare\PyViCareGazBoiler.py", line 18, in getAvailableBurners
              return self.service.getProperty("heating.burners")["components"]
            File "c:\Users\ChoSba\Desktop\PyViCare-master\PyViCare\PyViCareCachedService.py", line 26, in getProperty
              return readFeature(entities, property_name)
            File "c:\Users\ChoSba\Desktop\PyViCare-master\PyViCare\PyViCareService.py", line 17, in readFeature
              raise PyViCareNotSupportedFeatureError(property_name)
          PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.burners
          PS C:\Users\ChoSba>

**Comment by dennisheitmann** [comment]
I had the same error beginning at 24. January 2022 after around 20:20 CET. For me the replacement of `burner = t.burners[0]` with `burner = t.getBurner(0)` helped to solve the issue for me.

[Viessmann API to InfluxDB (using PyViCare)](https://gist.github.com/dennisheitmann/c35585b0c00ca109fcb383f01fb5eba1)

**Comment by woehrl01** [comment]
The `heating.burners` component is missing now from the response, whereas the actual data is still returned. As we use that value to find how many burners a device has, this currently fails.
This is most likely a bug in the API from Viessman. I'll have a look if a feasible workaround can be implemented.

**Comment by hnykda** [comment]
Hey, exactly the same issue :cry: . @dennisheitmann workaround works in CLI, but HomeAssistant obviously don't have this in. If there could be a workaround, it would be great.

**Comment by woehrl01** [comment]
I just received a response from the viessmann support that this change was by intention and the specific data will not come back. Therefore a workaround must be implemented.

**Comment by woehrl01** [comment]
Just published `2.16.1` including the workaround.
