### ISSUE TITLE
Vitovalor PT2 fuel cell gas consumption missing

### ISSUE THREAD

**Issue by Styx85** [openviess/PyViCare#246]
The Viessmann ViCare App is showing additional information for the fuel cell gas consumption.
So far pyvicare only reports heating and dhw gas consumption. 
Interestingly the app does not repor dhw gas consumption on its own, but the reported values for heating and dhw add up for the reported total gas values for heating. important: dhw is not equal fuel cell consumption so it really is different additional information for the PT2.

I guess it should be possible to access all three reported types:
heating 
dhw
fuel cell 

I'll try to gather a test case that it can be integrated into pyvicare.

**Comment by Styx85** [comment]
[VitovalorPT2_02_2022.json.txt](https://github.com/somm15/PyViCare/files/8027278/VitovalorPT2_02_2022.json.txt)

Ok, here is a dump from today. I guess I found the actual problem, but do not really know if it is situated here in pyvicare or a little bit further up in my setup (using the vicare plugin in homeassistant).

The Viessmann Api is actually reporting three different gas consumption values:
- heating.gas.consumption.heating 
- heating.gas.consumption.dhw
- heating.gas.consumption.total 

The Viessmann ViCare App is  showing the FuelCell gas consumption and gas burner gas consumption, but they seem to be  calculated values. 
So burner gas consumption equals heating.gas.consumption.heating + heating.gas.consumption.dhw 
and fuel cell gas consumption equals heating.gas.consumption.total - (heating.gas.consumption.heating  + heating.gas.consumption.dhw).

**Comment by woehrl01** [comment]
Fixed via #275
