### ISSUE TITLE
Lack of documentation for usage of setDomesticHotWaterCirculationSchedule

### ISSUE THREAD

**Issue by ol3k** [openviess/PyViCare#249]
Hi all,

I'm trying to change my DHWSchedules with the API but no params are working. 
The only param that works is disabling the schedule with "" = blank:

```
t.setDomesticHotWaterCirculationSchedule("")
{'data': {'success': True, 'reason': 'WARNING_PARAMETERS_CHANGED'}}
```

Is there any documentation or hint what param/JSON we should have used? Any try ends up in

```
Command failed with status code 502. Reason given was: INTERNAL_SERVER_ERROR
```

e.g. a output of a current Schedule:
```
t.getDomesticHotWaterCirculationSchedule())

{'active': True, 'default_mode': 'off', 'mon': [{'start': '05:50', 'end': '09:00', 'mode': 'on', 'position': 0}, {'start': '14:30', 'end': '21:30', 'mode': 'on', 'position': 1}], 'tue': [{'start': '05:50', 'end': '09:00', 'mode': 'on', 'position': 0}, {'start': '14:30', 'end': '21:30', 'mode': 'on', 'position': 1}], 'wed': [{'start': '05:50', 'end': '09:00', 'mode': 'on', 'position': 0}, {'start': '14:30', 'end': '21:30', 'mode': 'on', 'position': 1}], 'thu': [{'start': '05:50', 'end': '09:00', 'mode': 'on', 'position': 0}, {'start': '14:30', 'end': '21:30', 'mode': 'on', 'position': 1}], 'fri': [{'start': '05:50', 'end': '09:00', 'mode': 'on', 'position': 0}, {'start': '14:30', 'end': '21:30', 'mode': 'on', 'position': 1}], 'sat': [{'start': '07:30', 'end': '22:00', 'mode': 'on', 'position': 0}], 'sun': [{'start': '07:30', 'end': '22:00', 'mode': 'on', 'position': 0}]}
```

**Comment by nils2410** [comment]
For me it works like this:

`t.setDomesticHotWaterCirculationSchedule({"mon":[],"tue": [], "wed": [], "thu": [], "fri": [], "sat": [], "sun": []})`

`t.setDomesticHotWaterCirculationSchedule({"mon":[{"mode":"on","start":"00:00","end":"24:00","position":0}],"tue":[{"mode":"on","start":"00:00","end":"24:00","position":0}],"wed":[{"mode":"on","start":"00:00","end":"24:00","position":0}],"thu":[{"mode":"on","start":"00:00","end":"24:00","position":0}],"fri":[{"mode":"on","start":"00:00","end":"24:00","position":0}],"sat":[{"mode":"on","start":"00:00","end":"24:00","position":0}],"sun":[{"mode":"on","start":"00:00","end":"24:00","position":0}]})`

**Comment by ol3k** [comment]
thanks, I didn't tested this variation but it's working, closing here :-)
