### ISSUE TITLE
New Viessmann Developer Portal with free / paid Tiers

### ISSUE THREAD

**Issue by crazyfx1** [openviess/PyViCare#252]
I'm sure everyone here got the newsletter from Viessmann regarding the updated developer portal. The most interesting part for me is the free / paid pricing tiers for the API.
https://developer.viessmann.com/start/pricing.html

On the first glance it looks like nothing has changed for the free users. "Advanced" users could fetch additional data from the API.

You can check in the API documentation which data points are available for "Basic" or "Advanced" tiers: https://documentation.viessmann.com/static/iot/data-points

**Comment by oischinger** [comment]
To me it sounds like it will have an effect for some users. Looks like fuel cell and solar isn't part of the free package anymore

**Comment by adorobis** [comment]
The disappointing part is that some device types are not supported in the free tier...

**Comment by oischinger** [comment]
I wonder if they will attract a lot of customers paying 20€ a month for some sensor readings 🤔

**Comment by crazyfx1** [comment]
> To me it sounds like it will have an effect for some users. Looks like fuel cell and solar isn't part of the free package anymore

If you check our fuel cell implementation (https://github.com/somm15/PyViCare/blob/master/PyViCare/PyViCareFuelCell.py), there is not a single "heating.fuelCell.*" (which would be advanced tier) property used. 

Also all current solar properties implemented in https://github.com/somm15/PyViCare/blob/master/PyViCare/PyViCareDevice.py are in the basic tier.

It looks like all current properties are in the basic tier and all advanced properties are new and not implemented yet.

**Comment by nagelp** [comment]
They've lowered the price for "Advanced" now, to ~12 €/month (but only if you go for annual billing). Still too expensive to attract lots of developers. But better than 20... I've opened a [PR](https://github.com/somm15/PyViCare/pull/275) to add the Fuel Cell functions.

**Comment by zoogian** [comment]
Is there any work onging to be able to reduce the polling? Would be great if it is possible to limit what data to get, so the API calls not get that much, I have temp-sensors on most anyway, so would more or less only use the API to set target temp, for different heat circuits. and maybe DHW, but I dont need to pull all data every 60 sec...

**Comment by woehrl01** [comment]
@zoogian how do you call the API? Depending one the use case the amount can be configured freely.

**Comment by zoogian** [comment]
> @zoogian how do you call the API? Depending one the use case the amount can be configured freely.

I did not find a way in HA to adjust the polling to let say every 5 min, instead of 60 sec, and to remove sensors, or is one call counted for all values?

**Comment by crazyfx1** [comment]
The HA component fetches all values with 1 every 60 seconds. That's 1440 calls per day and within the limit of the free tier. 
If you have any problems with the HA component, please check this thread on the HA forums: https://community.home-assistant.io/t/viessmann-component/77873/807

**Comment by zoogian** [comment]
> The HA component fetches all values with 1 every 60 seconds. That's 1440 calls per day and within the limit of the free tier. If you have any problems with the HA component, please check this thread on the HA forums: https://community.home-assistant.io/t/viessmann-component/77873/807

I thought I hit the limit due to the usage of the app in the same time, but it seems there are at the moment other things as well going on. I am sorry, I thought this was about the HA integration, but this section is for the Viessmann API in general?
