### ISSUE TITLE
ViCare API now returns "heating.burners" feature - breaking burner enumeration logic?

### ISSUE THREAD

**Issue by lxpollitt** [openviess/PyViCare#254]
I'm using the Home Assistant ViCare module, which in turn uses PyViCare. Yesterday Home Assistant stopped reporting burner properties. I've done some limited debugging and I think it might be that the ViCare API has started returning "heating.burners" as a feature again (but without the legacy "components" property), which might be breaking the old legacy code method of enumerating burners here: https://github.com/somm15/PyViCare/blob/9b6612b5ae4f7b8c28f313fd783a267b1828ab9a/PyViCare/PyViCareDevice.py#L34-L35

Here's an example output I got from the ViCare API just now (with IDs obfuscated):

`{"data":{"properties":{"enabled":{"type":"array","value":["0"]}},"commands":{},"apiVersion":1,"uri":"https://api.viessmann.com/iot/v1/equipment/installations/1234/gateways/1234/devices/0/features/heating.burners","gatewayId":"1234","feature":"heating.burners","timestamp":"2022-05-23T15:30:29.096Z","isEnabled":true,"isReady":true,"deviceId":"0"}}`

Previously I don't think the API returned "heating.burners" as a feature. Or at least it is absent from the last dump I did a couple of months ago of the API features returned from my boiler.

I'm not confident in my diagnosis, so apologies if this diagnosis is incorrect!

**Comment by woehrl01** [comment]
Thanks @lxpollitt 

that‘s interesting. But if the `components` property is missing it should still fallback to the iteration logic.

**Comment by lxpollitt** [comment]
My Python knowledge is very rusty and limited, so I was not sure if a missing `components` property would get dealt with by the `suppress(PyViCareNotSupportedFeatureError)`, or get raised further up the stack resulting in the rest of the method not being executed. Or not result in any exception and just return no burners at that point?

**Comment by woehrl01** [comment]
@lxpollitt I just published `2.16.2` with the fix. Unfortunately I can‘t reproduce this on my device, so please have a look if this fixes your issue.

If not than please provide a dump of your device, so I can have a deeper look on what can be the root cause. 

It happens that the API returns different results for different devices.

**Comment by lxpollitt** [comment]
@woehrl01 Bumping the import version to 2.16.2 in Home Assistant looks to have resolved the issues for me and Home Assistant appears to be reporting the correct values for burner properties agin. Thank you for the extremely speedy fix!

**Comment by crazyfx1** [comment]
Small hint to the change from the Viessmann API documentation:
```
(2) Removal of "components"-section
We will continue with the removal of the listing feature remnants by removing the "components"-field from all features.
```

**Comment by woehrl01** [comment]
Thanks @crazyfx1 I think we should remove the optimization then. We also should have a look where we use that, too.

**Comment by lxpollitt** [comment]
@crazyfx1 Yes, I noticed that comment too. But interestingly, when I look at the dump of features returned by the API for my boiler from a couple of months ago, it did not return 'heating.burners' as a feature. Now it returns it as a feature (and without the 'components' property). So I think the API change I'm seeing on my boiler is subtly different than what they have flagged to expect.

**Comment by woehrl01** [comment]
Just removed all direct access of the `components` field in `2.16.4`.
