### ISSUE TITLE
Vissmann API restrictions

### ISSUE THREAD

**Issue by adorobis** [openviess/PyViCare#26]
Viessmann has introduced the restrictions on using their APIs. They have not yet published any details about those restrictions, they talk about daily and 15 minutes limits. Would it be possible to introduce a parameter to this integration to control the API calls intervals?
Some more info on viessmann forum:
https://www.viessmann-community.com/t5/Experten-fragen/Q-amp-A-Viessmann-API/qaq-p/127660

**Comment by crazyfx1** [comment]
See #22

**Comment by adorobis** [comment]
See #22
