### ISSUE TITLE
Dont work in viessmann Vitodens b2ha 200w

### ISSUE THREAD

**Issue by amgstone** [openviess/PyViCare#262]
Dont work in viessmann Vitodens b2ha 200w (preset_modes: comfort, eco, none)

![qwer](https://user-images.githubusercontent.com/63303107/184611387-62554020-19f0-4b65-94d6-2bce7371d1ab.jpg)

**Comment by woehrl01** [comment]
@amgstone can you please be more precise what you issue is. I don't understand. This repo is only the underlying library. For the home assistant integration please see: https://github.com/oischinger/ha_vicare
