### ISSUE TITLE
Heatpump: how to retrieve Thermal Performance and Energy input? 

### ISSUE THREAD

**Issue by wita-sec** [openviess/PyViCare#265]
Q: Is there a way with the PyViCare API to retrieve  Thermal Performance and Energy input?
I did not yet find this in the code.
If not, do you plan to add this feature to the API?
BTW, what you provide so far is really great, and it worked for me from scratch.

**Comment by crazyfx1** [comment]
We can only add values which are provided by the Viessmann API. For my heatpump Vitocal 200 I can't find those values in the API. 
To be honest I'm also not sure what those values mean (maybe you can write the german names ;) )

**Comment by wita-sec** [comment]
These are the German names: 
Energieverbrauch und Thermische Leistung
You can find this in the ViCare APP under Analyse/Energiebilanz
Its interesting for me to monitor the effectivity of the heatpump on a per day / per month / etc base.

Thank you for investigating

**Comment by wita-sec** [comment]
I have got some hints on this at the Viessmann Community.

heating.power.consumption.total
and
heating.power.consumption.dhw 
provide  data about the energy consumption 
see: https://www.viessmann-community.com/t5/The-Viessmann-API/Energieverbrauch-und-thermische-Leistung-per-API-abfragen/m-p/257309#M905

To PyViCareHeatPump.py (class HeatPump)  I added following lines of code for prototyping:

    @handleNotSupported
    def getPowerConsumptionToday(self):
        return self.service.getProperty("heating.power.consumption.total")["properties"]["day"]["value"][0]

    @handleNotSupported
    def getPowerConsumptionDomesticHotWaterToday(self):
        return self.service.getProperty("heating.power.consumption.dhw")["properties"]["day"]["value"][0]

It works.

**Comment by factor4** [comment]
I'm interested about that too. It would be great if that could be added. 👍 Thanks!

**Comment by bvm02** [comment]
Hi @wita-sec , @woehrl01 , @crazyfx1 

The feature data point "heating.power.consumption.total" and "heating.power.consumption.dhw" is not available in my API response of the Viesmann API for heat pump 300-G. 

Any other way to retrieve the energy consumption out of the heat pump ? I did notice there are "ViCare Compressor Hours Load Class 1/2/3/4/5" data points available but not sure how we should read these values.

Any pointers that someone can provide?

Thanks

**Comment by crazyfx1** [comment]
If the data is missing in the API we cannot do anything about it.

**Comment by bvm02** [comment]
> 

I understand but it feels very strange that nobody is monitoring energy consumption for their resp. heat pump so I assume there are other solutions out there, hence asking for feedback.
