### ISSUE TITLE
Boiler Supply Temperature for HeatPump

### ISSUE THREAD

**Issue by Kasper027** [openviess/PyViCare#266]
Hey, i need the Boiler Supply Temperature also for the Heatpump. Is it possible to get it?

**Comment by Kasper027** [comment]
can me help anyone?

**Comment by woehrl01** [comment]
Hi @Kasper027, this depends on our specific device if the value is available. If you can provide a dump of your API response (see Readme how to do). I can have a look if this is available and then add it to the API.

**Comment by Kasper027** [comment]
Hey @woehrl01 my problem ist solved now. The DataPoint was sensor.vicare_secondary_circuit_supply_temperature
