### ISSUE TITLE
Getting up to speed 

### ISSUE THREAD

**Issue by silverback658** [openviess/PyViCare#27]
Hi
I was trying to understand the interface (even if allegedly V will give us a all singing and dancing API) and in particular the structure of the requests and of the responses. I have tried with the debugger but the json is ?!???!?! and seemingly full of redundant information. 
Is there some description somewhere and can you point me to it? 
Any suggestions on how to get up to speed most welcome (my devel experience is ancient, C++ at the time STL was being born...)

Thanks
Michele

**Comment by adorobis** [comment]
There is a component for domoticz, seems it is implementing quite a lot parameters:
https://github.com/olivimo/pyvito
