### ISSUE TITLE
flue gas temperature

### ISSUE THREAD

**Issue by MichaelHultqvist** [openviess/PyViCare#271]
Hi, 

I've just found out about PyViCare and I find it very useful, but I have one question. I can see the flue gas temperature on my Vitodens 300 furnace in the Vicare app and according to the Viessmann documentation there is a datapoint called heating.flue.sensors.temperature.main which supposedly would be the what I am searching for, but I get the "PyViCareNotSupportedFeatureError:" message. Is this because I only have the basic plan or because it is not aviable from my furnace or because it is not implemented in PyViCare? And of course is this the parameter, which would tell me the flue gas temperature?

Thanks in advance.

**Comment by woehrl01** [comment]
@MichaelHultqvist Thank you, nice to hear that this library is useful for you.

If according to the documentation this is the right entry and you'll receive the not supported error, this field is not populated via the api. What you could do is creating a dump according to the Readme and have a look if the value is returned in an alternative property. It's known that the name can slightly differ.

What is the exact method you use from the library?

**Comment by MichaelHultqvist** [comment]
Thanks for the help. I now did a dump as suggested and the data point is not available in the dump, which could be related to the fact that I only use the basic plan. However I use the Getproperty method and get the response:
"PyViCareNotSupportedFeatureError: heating.flue.sensors.temperature.main", so I was wondering if it would also not be supported by PyViCare even if I had the advanced plan.

**Comment by woehrl01** [comment]
Unfortunately only the Viessmann support is likely able to answer you that question.

**Comment by MichaelHultqvist** [comment]
Yes you are right, and right now the advanced Viessman scheme is only available in Germany, so the answer will make no difference to me. Thanks for pointing out the dump option though, it has made it quite easy to see which data points I can get 👍
