### ISSUE TITLE
PyViCareCommandError can sometimes get a string

### ISSUE THREAD

**Issue by lukx** [openviess/PyViCare#272]
Hey,
in [`__init__` of PyViCareCommandError](https://github.com/somm15/PyViCare/blob/69496fa4aafe034d133946577b8b26359e4ccea4/PyViCare/PyViCareUtils.py#L120), the `response` is expected to be a dictionary / map.
However, in [L60](https://github.com/somm15/PyViCare/blob/master/PyViCare/PyViCareUtils.py#L60) we are instantiating it with a String argument, possibly leading to the problem observed by @Friedi1970 in [this issue of Home-Assistant Core](https://github.com/home-assistant/core/issues/73064).

Possible solution could be to refine the error handling in handleAPICommandErrors? @woehrl01 what's your opinion?

(happy to contribute and test once you give directions)

**Comment by woehrl01** [comment]
@lukx Nice catch. Yes, this is bug. I guess the best option is to extend the "PyViCareCommandError", to still be able to pass the function name, but also the response.

An alternative is to handle the possibility to pass a string as an argument and just use that in the msg.

You are welcome to create a PR.
