### ISSUE TITLE
IndexError: list index out of range for device

### ISSUE THREAD

**Issue by senufo** [openviess/PyViCare#274]
Hi,
I need help understanding how to configure API access.
I have created a developer account and a new OAUTH client with:
```
     Name: PyViCare
     Google reCAPTCHA: Disabled
     Redirect URIs: vicare://oauth-callback/everest

```
I used the demo program with the client id, my email and my password. The connection is going well I have the trace in the dashboard of Viessman but it returns me no device!

The vicare app works well with my boiler (VITODENS 222F).

Is there an additional action to do to associate the boiler with my developer account?

Thank you for your help
Senufo

**Comment by crazyfx1** [comment]
The problem is most likely that you've created a new account. You should have logged in with your existing vicare account to the developer portal as stated in the readme.

**Comment by senufo** [comment]
Thanks.
I started again with the same identifiers as on the application and it worked but I had to wait 24 hours before being able to get the informations
