### ISSUE TITLE
Donations 

### ISSUE THREAD

**Issue by cagnulein** [openviess/PyViCare#279]
Hi @somm15 why don't you add a buy me a coffee link or something in this repository (sponsorship item here on github).

I would like to donate something since i'm using this integration a lot

Thanks for your hard work!

**Comment by woehrl01** [comment]
Thank you @cagnulein for offering donations to the project. 

Even though this repo is officially under @somm15 account, the current maintainers are @crazyfx1 and myself (@woehrl01). 

If you want to sponsor me, you can do that via [Github sponsorship](https://github.com/sponsors/woehrl01). Thanks!

**Comment by cagnulein** [comment]
@woehrl01 done! thanks!
also just a quick question: are decimal supported to set the target temperatures? i did a quick test today and it seemed that it cast it always to integer 

thanks

**Comment by woehrl01** [comment]
Thanks a lot. This is highly appreciated. 🙏

Yes, the value gets casted to integer. Can you please check the following response value for your device: https://github.com/somm15/PyViCare/blob/59a382bd1067429b36734aa4a2d773a559cf903f/tests/response/Vitodens200W.json#L259

If this shows a sub-total stepping, we can have a look to implement some logic around that.

**Comment by cagnulein** [comment]
still 1 as step for me too :( it's strange because from the viessman app i can change the 0.5

doesn't the app use the same api?

**Comment by cagnulein** [comment]
sorry i was wrong

https://github.com/somm15/PyViCare/pull/177/files

it has 0.5 for stepping

**Comment by zoogian** [comment]
Trying to get to test this, but got a massive amount of API calls.. and the viguide page stopped working for me, now only access the heatpump via ViCare app...  I liked the webinterface of Viguide..

**Comment by cagnulein** [comment]
@zoogian which is the topic? are you talking about this ticket or PyViCare in general?
