### ISSUE TITLE
API broken?

### ISSUE THREAD

**Issue by sweh** [openviess/PyViCare#284]
Hi there,

since 01:00 UTC, I don't get data from the API. Login seems to work, but every data request results in a

`PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: <property>`

e.g.

`PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: heating.dhw.sensors.temperature.hotWaterStorage`.

Can someone confirm it? Is this a temporary problem or did the Viessmann api change?

**Comment by crazyfx1** [comment]
They announced an API change but it should go live in January 2023. 
https://documentation.viessmann.com/static/changelog

So I hope it's just temporarily.

**Comment by sweh** [comment]
API is back again. Nevermind,
