### ISSUE TITLE
The temperature reading precision has reduced after 10pm December 4th (CET)

### ISSUE THREAD

**Issue by hnykda** [openviess/PyViCare#287]
Hi,

I have noticed that the temperature sensor has been returning much coarser readings (and they are updated much less often). It happened suddenly after December 4th at 10pm. Here is a chart:

![2022-12-08_21-44](https://user-images.githubusercontent.com/2741256/206564594-108b6539-f902-409a-9285-b035b0d4cd9e.png)

and here it is plotted against another of my temperature sensors (this one is from a ventilation, so it usually shows about a few degrees more):

![2022-12-08_21-45](https://user-images.githubusercontent.com/2741256/206564598-aec54114-8eb3-4301-87b7-ef1702b6e8bf.png)

It seems like the vicare sensor _is_ still tracking the reality, but at much slower rate and coarser way. Has anyone else observed the same? Is it a known API change (if yes, I am starting to get quite disappointed with Viessman 👎 ), I haven't [found anything in their changelog](https://documentation.viessmann.com/static/changelog)? The ViCare Android app also shows just a whole integer value now 😕 .

**Comment by woehrl01** [comment]
@hnykda The reduction of the resolution has been done quite a few months ago. I guess this was a rolling update and know you are affected. Unfortunately this is how the official Viessman API shifts to “reduce traffic” and to push users to the (very) expensive paid tiers. There is absolutely nothing we can do about it.

**Comment by hnykda** [comment]
Got, I see, totally understandable that you can't do anything about it. Thank you a lot for your work.

Related posts for viessman forum:
1. https://www.viessmann-community.com/t5/The-Viessmann-API/Aussentemperatur-wird-ploetzlich-nur-noch-in-1-K-angegeben-ueber/td-p/278251
2. https://www-viessmann--community-com.translate.goog/t5/The-Viessmann-API/Werte-der-API-ploetzlich-gerundet-geglaettet-bzw-nicht-mehr/td-p/237282?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp
