### ISSUE TITLE
Any plans to support the additional endpoints in paid API tier?

### ISSUE THREAD

**Issue by michis0806** [openviess/PyViCare#289]
Hi,

I have just installed Viessmanns smart thermostats and room sensors and would like to access the data via the API. I learned that this is only possible with the paid tier for 140€ p.a.
Are the endpoints already supported by PiViCare?

thanks!
Michael

**Comment by oischinger** [comment]
Hi @michis0806 
are you talking about these data points: 
![image](https://user-images.githubusercontent.com/7779765/210625051-737e4e95-bf65-4af9-a331-8e011fa237ef.png)
(see bottom of https://documentation.viessmann.com/static/iot/data-points )

if you have the paid API and at least one of these thermostats you could provide a dump of your API data to help implementing this. See https://github.com/somm15/PyViCare#more-different-devices-for-test-cases-needed

**Comment by oischinger** [comment]
I was able to obtain some by myself:
PR is started here:
https://github.com/somm15/PyViCare/pull/293

**Comment by woehrl01** [comment]
Completed via #293
