### ISSUE TITLE
Vitocal BWC301.C06 : No devices

### ISSUE THREAD

**Issue by Quelbazar** [openviess/PyViCare#309]
Hi,

I own a (new...) heatpump Vitocal BWC301.C06 with Vitoconnect. I'm not sure why PyViCare or Home assistant is not returning any values:

When initializing HA addon, or when running this python script (from PyVicare Readme) :

> import sys
> import os
> from PyViCare.PyViCare import PyViCare
> 
> client_id = os.getenv("PYVICARE_CLIENT_ID", "INSERT CLIENT_ID")
> email = os.getenv("PYVICARE_EMAIL", "myemail@mydomain")
> password = os.getenv("PYVICARE_PASSWORD", "mypassword")
> 
> vicare = PyViCare()
> vicare.initWithCredentials(email, password, client_id, "token.save")
> 
> with open(f"dump.json", mode='w') as output:
>    output.write(vicare.devices[0].dump_secure())

Init with my credentials is OK.

The result is :

> IndexError: list index out of range

PyViCare does not seem to detect any devices

However, when running this API call

> curl -X GET "https://api.viessmann.com/iot/v1/equipment/installations/XXXXXX/gateways/YYYYYYYYYYYYYYYY/devices/0/features" -H "Authorization: Bearer eyJraWQiOiJmMzI3Y2NmOC.....0"

I have a correct answer with a lot of "properties"

[output_anon.json.txt](https://github.com/somm15/PyViCare/files/11380182/output_anon.json.txt)

Why does PyViCare not recognize them ?

**Comment by woehrl01** [comment]
Hi @Quelbazar ! Thank you, can you please forward the output of the "/devices" request? It looks like there is a unknown tag associated to that device

**Comment by Quelbazar** [comment]
> Hi @Quelbazar ! Thank you, can you please forward the output of the "/devices" request? It looks like there is a unknown tag associated to that device

Hi Lukas,

Here is the output of GET "https://api.viessmann.com/iot/v1/equipment/installations/XXXXXX/gateways/YYYYYYYYYYYYYYYY/devices" 

[devices.json.txt](https://github.com/somm15/PyViCare/files/11380496/devices.json.txt)

Is this what you needed ?

**Comment by woehrl01** [comment]
yes, thank you!

**Comment by Quelbazar** [comment]
Better but not OK : 

I no longer get an error message, but no items are detected. 

Contents of the dump.json file generated with the above script:

> {
>     "data": []
> }

**Comment by Quelbazar** [comment]
I tried to understand, but I definitely don't have the skills for python anymore: The last time I wrote code, it was in the last century...
Sorry for that.

However:

 __extract_devices(self): The device.id value used to define acessor was "gateway".  
However, for buildGetPropertyUrl, the "accessor.device_id" has to be "0"

So I added on  __extract_devices(self) an ugly 

                    if device.id = "gateway":
                        device.id = "0"

Now a 

> device = vicare.devices[0]
> t = device.asAutoDetectDevice()
> print(t.service.getProperty("heating.sensors.temperature.outside")["properties"]["value"]["value"])

works fine
However a

> device = vicare.devices[0]
> t = device.asAutoDetectDevice()
> print(t.getOutsideTemperature)

returns

> <bound method handleNotSupported.<locals>.feature_flag_wrapper of <PyViCare.PyViCareHeatingDevice.HeatingDevice object at 0x7f98193b20>>


I am defeated, I give up.

**Comment by woehrl01** [comment]
@Quelbazar I just published a fix which should make the detection of the device id "0" work.

Can you please try using `asHeatPump` instead of `asAutoDetectDevice`. If this does not work, can you please share the dump which gets generated?

**Comment by Quelbazar** [comment]
Works fine. Thanks !
Some functions work only  with `asHeatPump` :  `getBufferMainTemperature` for example.
My tests were partially wrong : I used `print(t.getOutsideTemperature)` instead of `print(t.getOutsideTemperature())`

Many Thanks !

Here is the dump :

[dump.json.txt](https://github.com/somm15/PyViCare/files/11415357/dump.json.txt)

**Comment by woehrl01** [comment]
Great!
