### ISSUE TITLE
Many measurements in one request feature

### ISSUE THREAD

**Issue by justinasjaronis** [openviess/PyViCare#32]
Viessmann limits rate quite heavily.  If we try to fetch many parameters often, we quickly run in threshold:

API calls rate limit has been exceeded. Please wait until your limit will renew. Limit will be reset on Tue, 31 Mar 2020 16:20:36 +0000

Do we have a moethod to retrieve many readings in single call ? I see it's possible to obtain all data in that huge features json request.

**Comment by michelde** [comment]
See here: https://github.com/somm15/PyViCare/pull/28

**Comment by somm15** [comment]
Already fixed
