### ISSUE TITLE
Support for Ventilation

### ISSUE THREAD

**Issue by pduchnovsky** [openviess/PyViCare#321]
Hello !

Would you please consider adding support for managing of connected Ventilation to the Heat Pump, such as Vitovent 200-W
This is already supported by API, the data is there when you have connected Ventilation system to the heat pump.

For me personally, most important feature is possibility to trigger 'Intensive ventilation' mode, which triggers max level of ventilation for defined amount of time (predefined in heat pump settings)
Then it would be possible to integrate to home assistant integration.

**Comment by aaschmid** [comment]
Maybe you can test my PR, see #326. It is far from ready but at least works for my local tests. Still some discussions open but afterwards I will finish it and hope to get it merged ;-)

**Comment by pduchnovsky** [comment]
> Maybe you can test my PR, see #326. It is far from ready but at least works for my local tests. Still some discussions open but afterwards I will finish it and hope to get it merged ;-)

Awesome ! Would you mind showing me short example code on how to work with it please, just need to change between intensive ventilation and standard scheduled modes

I am asuming this is base code and then how do you go on with it ?
I could dust off some python knowledge and investigate myself just wanted to ask since you probably already have some code yourself :)

```
import sys
import logging
from PyViCare.PyViCare import PyViCare

client_id = "xxxx"
email = "xxxx"
password = "xxxx"

vicare = PyViCare()
vicare.initWithCredentials(email, password, client_id, "token.save")
device = vicare.devices[0]
```

**Comment by aaschmid** [comment]
Hi @pduchnovsky, 
here is some example code which I used to test locally:

```
vicare = PyViCare()
vicare.initWithCredentials(email, password, client_id, "token.save")

device = vicare.devices[0].asVentilation()
print(device.getActiveMode())
print(device.getAvailableModes())
print(device.getActiveProgram())
print(device.getAvailablePrograms())
print(device.getSchedule())
print(device.service.fetch_all_features())
print(device.service.getProperty("ventilation"))
print(device.service.getProperty("ventilation.operating.modes.active"))
```

Hope this helps. As soon as I get some response from the maintainers, I can also create documentation and test code.

**Comment by pduchnovsky** [comment]
@aaschmid thanks ! But for some reason it doesn't work for me -.-

![image](https://github.com/somm15/PyViCare/assets/54581833/926aed68-938e-41a6-a7a5-a845f0cbc24c)

**Comment by aaschmid** [comment]
Hard to say what went wrong from so far away ...
Do you have more `devices`? Could you print what the `devices` are about (maybe without serial nos and such sensible information?)

**Comment by pduchnovsky** [comment]
I have only one heat pump device (with connected ventilation system)

It won't print much details:
```
>>> print(vicare.devices)
[<PyViCare.PyViCareDeviceConfig.PyViCareDeviceConfig object at 0x7fd46ac90d50>]
>>> print(vicare.devices[0])
<PyViCare.PyViCareDeviceConfig.PyViCareDeviceConfig object at 0x7fd46ac90d50>
>>> print(vicare.devices[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: list index out of range
```

But the error `AttributeError: 'PyViCareDeviceConfig' object has no attribute 'asVentilation'` makes me think it somehow does not even understand the new `asVentilation` value

Also:
```
>>> print(dir(vicare.devices[0]))
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'asAutoDetectDevice', 'asFuelCell', 'asGazBoiler', 'asGeneric', 'asHeatPump', 'asHybridDevice', 'asOilBoiler', 'asPelletsBoiler', 'asRadiatorActuator', 'asRoomSensor', 'device_id', 'device_model', 'dump_secure', 'getConfig', 'getId', 'getModel', 'get_raw_json', 'isOnline', 'service', 'status']
```
^ no `asVentilation` there

Maybe my imports are wrong or something ? I have cloned your repo with branch ventilation here so should be fine.

**Comment by aaschmid** [comment]
Yes, seems indeed to be a problem with the "wrong" source code. I just checked that everything is submitted, which actually is. Here's how it looks like at my system:

<img width="900" alt="grafik" src="https://github.com/somm15/PyViCare/assets/567653/847f1fda-cbb2-4240-873e-3caf0388cdf9">

**Comment by edeckert** [comment]
@aaschmid 
I tested your PR #326 and it worked perfectly for my Vitovent 300-W.
It would be really great, if you open the pull request (instead of a draft).

I would like integrate my ventilation system into my smart home (home assistant) and this feature is needed from PyViCare to integrate it into Home Assistant.

I tested it with the following test script:
```
vicare = PyViCare()
vicare.initWithCredentials(email, password, client_id, "token.save")

device = vicare.devices[0].asVentilation()
print(device.activateProgram("eco"))
print(device.getActiveMode())
print(device.getAvailableModes())
print(device.getActiveProgram())
print(device.getAvailablePrograms())
print(device.getSchedule())
print(device.setActiveMode("standby"))
print(device.activateProgram("eco"))
print(device.deactivateProgram("eco"))
```

and the result was the following:
```
{'data': True}
ventilation
['standby', 'standard', 'ventilation']
levelTwo
['standby', 'comfort', 'eco', 'holiday', 'levelFour', 'levelOne', 'levelThree', 'levelTwo']
{'active': True, 'mon': [{'start': '00:00', 'end': '08:00', 'mode': 'levelTwo', 'position': 0}, {'start': '08:00', 'end': '21:00', 'mode': 'levelThree', 'position': 1}, {'start': '21:00', 'end': '24:00', 'mode': 'levelTwo', 'position': 4}], 'tue': [{'start': '00:00', 'end': '08:00', 'mode': 'levelTwo', 'position': 0}, {'start': '08:00', 'end': '21:00', 'mode': 'levelThree', 'position': 1}, {'start': '21:00', 'end': '24:00', 'mode': 'levelTwo', 'position': 4}], 'wed': [{'start': '00:00', 'end': '08:00', 'mode': 'levelTwo', 'position': 0}, {'start': '08:00', 'end': '21:00', 'mode': 'levelThree', 'position': 1}, {'start': '21:00', 'end': '24:00', 'mode': 'levelTwo', 'position': 4}], 'thu': [{'start': '00:00', 'end': '08:00', 'mode': 'levelTwo', 'position': 0}, {'start': '08:00', 'end': '21:00', 'mode': 'levelThree', 'position': 1}, {'start': '21:00', 'end': '24:00', 'mode': 'levelTwo', 'position': 4}], 'fri': [{'start': '00:00', 'end': '08:00', 'mode': 'levelTwo', 'position': 0}, {'start': '08:00', 'end': '21:00', 'mode': 'levelThree', 'position': 1}, {'start': '21:00', 'end': '24:00', 'mode': 'levelTwo', 'position': 4}], 'sat': [{'start': '00:00', 'end': '08:00', 'mode': 'levelTwo', 'position': 0}, {'start': '08:00', 'end': '21:00', 'mode': 'levelThree', 'position': 1}, {'start': '21:00', 'end': '24:00', 'mode': 'levelTwo', 'position': 4}], 'sun': [{'start': '00:00', 'end': '08:00', 'mode': 'levelTwo', 'position': 0}, {'start': '08:00', 'end': '21:00', 'mode': 'levelThree', 'position': 1}, {'start': '21:00', 'end': '24:00', 'mode': 'levelTwo', 'position': 4}]}
{'data': True}
{'data': True}
{'data': True}
```

I have to mention that i got an error with the functions
``` 
device.activateProgram("eco")
device.deactivateProgram("eco")
```
I got an error because of the cacheDuration of 60. Then i put it down to 1 and it worked as expected.

**Comment by aaschmid** [comment]
Thanks for the feedback. To be honest I just use a local version of it deploying a little web app to abstract the ViCare APIs using "my" enhanced version of PyViCare in the backend...

**Comment by woehrl01** [comment]
Completed via #326, thanks @aaschmid

**Comment by CFenner** [comment]
@aaschmid Created https://github.com/home-assistant/core/pull/106467 to bring changes to HA component.
