### ISSUE TITLE
PyViCareInvalidCredentialsError

### ISSUE THREAD

**Issue by williwacker** [openviess/PyViCare#322]
Hi,
Since today afternoon I am getting PyViCareInvalidCredentialsError with the latest version of PyViCare.
Now I went back to 2.20.0 and it is working again.
Any idea what is causing this?
Thanks

**Comment by dennisheitmann** [comment]
I had the same problem. I tested downgrading to 2.20.0. After downgrade it worked again, then I upgraded to the latest version 2.28.1 and it still works... strange...

**Comment by dennisheitmann** [comment]
If I then remove the token.save file, it does not work again. So the token might be the problem.

**Comment by dennisheitmann** [comment]
2.25.0 is the newest version which works

**Comment by dennisheitmann** [comment]
I guess the authentification endpoint v3 is not working properly on the Viessmann servers, as 2.25.0 uses v2 and all newer versions use v3.

**Comment by dennisheitmann** [comment]
Now 2.28.1 works again. I guess Viessmann had some problems with their systems.

**Comment by dennisheitmann** [comment]
In my opinion, the issue is resolved (was no problem of the library) and can be closed.
