### ISSUE TITLE
Question: System pressure

### ISSUE THREAD

**Issue by grobihh** [openviess/PyViCare#329]
Hi,
Thanks for the great work.
I cannot find the system pressure.
In the ViCare APP the system pressure is shown but I did not find any call in your library.
Is it not implemented?

**Comment by woehrl01** [comment]
Hi @grobihh

Unfortunately not every value is accessible via the API, you can create a dump of the response as described in the Readme and have a look at the resulting json to see if the value is part of your response. If yes, it can be easily added to the library.

**Comment by grobihh** [comment]
I cannot see it in the API dump.
The pricing details suggests that pressure is only available in the payed subscriptions. 😟
https://developer.viessmann.com/start/pricing.html
