### ISSUE TITLE
Query directly the Vitoconnect device ?

### ISSUE THREAD

**Issue by somm15** [openviess/PyViCare#34]
As mentioned in another issue, the port "56747/tcp" is opened on the Vitoconnect.
I don't know yet which service is running there.
I should also try MitM to check if communication could be intercepted. 
The goal is to free ourself from the could and have local polling.

**Comment by adorobis** [comment]
Hi @somm15 
Any progress on that? Recent issues with cloud API are a bit annoying...

**Comment by somm15** [comment]
There were no reaction so I thought no interest. 
I didn't really spend effort there so far but I should.
I don't like relying on this could system.

**Comment by adorobis** [comment]
Let me know if there is a way I could help although my programming skills might not be strong enough to make any major work.

**Comment by hpapagaj** [comment]
Local control would be awesome.

**Comment by sebekhtc** [comment]
I checked the h/w of the vito, it's based on Atheros AR9331 if it may help.

**Comment by somm15** [comment]
https://reverseengineering.stackexchange.com/questions/23222/extract-repack-eeprom-dump
Some already tried at least.
