### ISSUE TITLE
Accuracy of sensor.vicare_supply_temperature

### ISSUE THREAD

**Issue by mho21git** [openviess/PyViCare#341]
Hi all,
the accuracy (precision, resolution) of sensor.vicare_supply_temperature is 1°C
But I'm sure, it is provided and must be 0,1 °C
heating.circuits.N.sensors.temperature.supply
![grafik](https://github.com/somm15/PyViCare/assets/134859034/3c2cb714-e824-4060-ae27-fabdae74b9d4)

**Comment by CFenner** [comment]
For me the sensors seem to work, but for some reason the default display accuracy is different. 

<img width="396" alt="Bildschirmfoto 2023-11-24 um 16 14 27" src="https://github.com/somm15/PyViCare/assets/9592452/3bee2e51-3975-4ee1-b350-3eb40c2c3fd0">
<img width="399" alt="Bildschirmfoto 2023-11-24 um 16 14 51" src="https://github.com/somm15/PyViCare/assets/9592452/ff57fa25-b973-4f78-9d75-143cc9a22d00">

**Comment by stobies** [comment]
I seem to recall a discussion on the Viessmann developer site, where people were mentioning that Viessmann have reduced the accuracy of the data that they provide through the API.

**Comment by crazyfx1** [comment]
Yes this was my thread on the viessmann page, only available in german.
https://www.viessmann-community.com/t5/The-Viessmann-API/Werte-der-API-ploetzlich-gerundet-geglaettet-bzw-nicht-mehr/td-p/237282

**Comment by CFenner** [comment]
<img width="332" alt="Bildschirmfoto 2023-11-26 um 15 01 00" src="https://github.com/somm15/PyViCare/assets/9592452/92e91b9f-f65f-46dc-8839-ab3f04b1dd5c">

**Comment by woehrl01** [comment]
As @crazyfx1 mentioned, this is an active change made by Viessmann over a year ago. If you subscribe to the (pricy) subscription I have been told that you have higher granularity of the values. Nothing we can change from perspective of the library.
