### ISSUE TITLE
Two API calls counted at Viessmann

### ISSUE THREAD

**Issue by readonly24** [openviess/PyViCare#357]
PyViCare version is 2.32.0

This small script always adds two API calls at Viessmann, can anyone please explain? Thanks.

```
import sys
import logging
from PyViCare.PyViCare import PyViCare

client_id = "INSERT CLIENT ID"
email = "email@domain"
password = "password"

vicare = PyViCare()
vicare.initWithCredentials(email, password, client_id, "token.save")
device = vicare.devices[1]

t = device.asAutoDetectDevice()

print("Brennertemperatur:", t.getBoilerTemperature())
```

**Comment by woehrl01** [comment]
Hi @readonly24 there are three API calls:

* Login
* Getting the device list
* Calling the properties of that device

I assume the last two calls are counted to your limit.
