### ISSUE TITLE
Discussion: Moving to a dedicated org

### ISSUE THREAD

**Issue by woehrl01** [openviess/PyViCare#377]
Hi there,

Seeing that there are new forks happening because of limited capacity around current maintainers, in combination with not enough administrative rights, I suggest we should revive the idea of moving this project to a dedicated org "PyViCare", where maybe the home assistant integration could be located as well. So those are not tied anymore to individuals, but more to a group allowing things move forward without having to constantly adding new libraries/repos/pypi confusing the outside of the community especially new people. 

Looking forward to your feedback @crazyfx1 @CFenner @oischinger and especially @somm15 as you would need to transfer the repo.

Tasks:
- [x] Create new organisation
- [x] Transfer Github repo
- [x] Create new pypi release ~~under new name~~
- ~~Create new pypi release under old name referencing new pipy package.~~

**Comment by crazyfx1** [comment]
Yes, this should have been done when we took over from somm15. I hope he is available to transfer.

**Comment by CFenner** [comment]
That's a great idea, however @somm15 seems not to be active on GH anymore. Alternative could be to create yet another fork on the new org.

I'm about to [switch the HA internal integration](https://github.com/home-assistant/core/pull/124107) to a new release from my fork as there are some deprecations and bugs we need to tackle now. But I guess it's no big deal to switch it back again once the new org is created.

**Comment by woehrl01** [comment]
Thank you for your feedback. I created the organization https://github.com/openviess  and added you both already. I hope @somm15 is willing to transfer the repo, so links and stars are retained. If we haven't heard for a while, we can also just shift the repo there.

**Comment by CFenner** [comment]
> Create new pypi release under old name referencing new pipy package.

We probably could keep on using https://pypi.org/project/PyViCare/, just need to link to the new repo slug.

**Comment by somm15** [comment]
Hello, I'm not dead :-)
I can transfert the ownership to the new org. I don't have time for this project anymore (and for a very long time).

**Comment by somm15** [comment]
@woehrl01 Could you please grant me the permission to create repos on the new org? Otherwise, I can't transfer.

**Comment by CFenner** [comment]
@somm15 I made you an owner as well. Could you add us as owners to [the PyPi project](https://pypi.org/project/PyViCare/) as well? That way we can continue to use the same package name.
Thanks!

**Comment by CFenner** [comment]
@somm15 would you give it another try?

**Comment by somm15** [comment]
Well, the issue is still there: "You don’t have the permission to create public repositories on openviess"
You're the only person listed in openviess.

**Comment by woehrl01** [comment]
@somm15 I just saw that there has been a "failed invitation" to your account, can you please accept and then retry?

**Comment by somm15** [comment]
It should done now !
Thank you.

**Comment by CFenner** [comment]
@woehrl01 can we reuse [pyvicare on pypi](https://pypi.org/manage/project/pyvicare/collaboration/)?

Can you add [me](https://pypi.org/user/Hafenstrand/) as a maintainer?

**Comment by woehrl01** [comment]
@CFenner I can't modify the maintainers on pyvicare, @somm15 likely has to give this to you.

**Comment by crazyfx1** [comment]
You can push new PyViCare versions to pypi by using the already existing Github actions. No need to be maintainer.

**Comment by CFenner** [comment]
True, but I think it would be nice to use trusted publishing together with poetry to manage and upload the project.

https://packaging.python.org/en/latest/guides/tool-recommendations/#uploading-to-pypi
> For projects hosted on GitHub, it is recommended to use the [trusted publishing](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#trusted-publishing), which allows the package to be securely uploaded to PyPI from a GitHub Actions job.
