### ISSUE TITLE
Error during setup of component vicare

### ISSUE THREAD

**Issue by adorobis** [openviess/PyViCare#41]
Since a few hours the vicare API don't work anymore although the mobile app is still working ok (so probably no problem with number of calls). The following errors are returned:
```
 python3 -c "from PyViCare.PyViCareDevice import Device; from PyViCare.PyViCareGazBoiler import GazBoiler; t=GazBoiler('xxx@yyy.com','zzzzzzzzzzzz,'/tmp/vicare_token.save');print(t.setMode('dhw'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/PyViCare/PyViCareDevice.py", line 46, in __init__
    self.service = ViCareService(username, password, token_file, circuit)
  File "/usr/local/lib/python3.7/site-packages/PyViCare/PyViCareService.py", line 58, in __init__
    self._getInstallations()
  File "/usr/local/lib/python3.7/site-packages/PyViCare/PyViCareService.py", line 219, in _getInstallations
    self.id=self.installations["entities"][0]["properties"]["id"]
KeyError: 'entities'
```
the issue is also described in the home-assistant / core git issue suggesting some change in the API:
[ViCare Vissmann Component error #41725](https://github.com/home-assistant/core/issues/41725)
Any clues?

**Comment by adorobis** [comment]
Seems that there was something broken on Viessmann's API side, it works ok again now.

**Comment by membersound** [comment]
Anyways, wouldn't it be worth investigating an api upgrade to `/v2`, if obviously exists? Because vissmann might drop v1 in the future, plus there might be more features in v2?

**Comment by somm15** [comment]
Is there a v2?

**Comment by adorobis** [comment]
Looks like there was some issue on Viessmann API side, resolved now.
