### ISSUE TITLE
Can't run test script

### ISSUE THREAD

**Issue by dr-boss** [openviess/PyViCare#42]
I receive the error (if I installed by pip or by github and setup.py install). The test is simple:
`import sys
import logging
sys.path.insert(0, 'PyViCare')
from PyViCare.PyViCareDevice import Device
from PyViCare.PyViCareGazBoiler import GazBoiler
from PyViCare.PyViCareService import ViCareService
from PyViCare.PyViCare import ViCareSession

t=GazBoiler("piotr@email","pass2","token.save")
print(t.getDomesticHotWaterConfiguredTemperature())
`
and the error is:
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from PyViCare.PyViCareDevice import Device
  File "PyViCare/PyViCare.py", line 1, in <module>
    from PyViCare.PyViCareGazBoiler import GazBoiler
ModuleNotFoundError: No module named 'PyViCare.PyViCareGazBoiler'; 'PyViCare' is not a package

**Comment by adorobis** [comment]
It still works for me ok. Just install the PyVicare using pip e.g. `pip3 install PyVicare`, below is an example of test script which you can just run as single command (I have just tested it on a fresh install of Ubuntu Server):
```
python3 -c "from PyViCare.PyViCareDevice import Device; from PyViCare.PyViCareGazBoiler import GazBoiler; t=GazBoiler('youremail@domain.xxx','yourVicarepassword','/tmp/vicare_token.save');print(t.getPrograms())"
```
in my case it returns:
`['active', 'comfort', 'eco', 'external', 'holiday', 'normal', 'reduced', 'standby']`
Also the test script from readme file here works all ok (except for commands not supported by my system).

**Comment by dr-boss** [comment]
thx, your test work fine, I will look my code to find error. But like in another implementation of Viessmann API set program (for comfort or eco) not work for my Vitodens :-(. I can set the temperature but I can't activate program. Only set mode is fill supported, but for programs only holiday program can be activate or deactivate by API

ps. I added non necessery line: sys.path.insert(0, 'PyViCare')
