### ISSUE TITLE
getErrorHistory() - how does it work?

### ISSUE THREAD

**Issue by adorobis** [openviess/PyViCare#43]
Hello,
Is there a good explanation on how the getErrorHistory() function works? I'd like to capture the error when it happens, but I can see that sometimes they show up in "active_error" section of returned json in "new" or in "current". When reset on the heater they sometimes move to "gone" section but sometimes disappear from "active_error" completely. Anyone understands the logic?
And btw is there a way to reset the error via API?

**Comment by crazyfx1** [comment]
Error history is not available anymore in V2.
