### ISSUE TITLE
Info about Vitoconnect

### ISSUE THREAD

**Issue by cagnulein** [openviess/PyViCare#46]
Hi guys, i found you because I would like to put a Vitoconnect OT2 (opentherm) to my Viessman 111W.

It should very simple but I have a question about it. The OT2 has an opentherm thermostat too and Viessman tell me that the installation of this thermostat is mandatory with OT2.

Is it real? I don't understand why is mandatory: i mean, the Vitoconnect should act as a "remote keyboard" for my boiler and if there isn't any thermostat, it should simple keep the hot water and the floor heating to the set point that I set.

Infact, now my heating system has composed by the Viessman and 10 dumb thermostats linked by wire to electric valves without any thermostat connected directly to my boiler.

I'm sorry about creating an issue for this topic, but i would like to use the knowledge of this community :D

**Comment by adorobis** [comment]
I have looked at installation manual for OT2 and it mentions the thermostat OT1 as optional so in my opinion it is not mandatory. But to be sure I would write to Viessmann support, they are pretty responsive (at least in Poland)

**Comment by cagnulein** [comment]
hi @adorobis thanks for answering me 👍 
if you have a contact in poland, could you please write to them? I don't trust so much the italian assistance of Viessmann :)
I also believe that it should be an optional

**Comment by adorobis** [comment]
OK, I have written to the regional support, let's see what they answer. In the mean time you can also go to the Viessmann forum - the Viessmann staff is quite responsive there. It is mostly in German but they also answer to questions in English (with help of google translate you can benefit from both).
https://www.viessmann-community.com/

**Comment by cagnulein** [comment]
@adorobis https://www.viessmann-community.com/t5/Gas/Vitodens-111-W-amp-Vitoconnect-OT2/m-p/148834#M49474 done thanks :)

**Comment by adorobis** [comment]
I have received answer from the service in Poland:
"The installation of a Vitotrol 100 OT1 thermostat is required for the correct functioning of the remote control. This thermostat reads the temperature in the room and sends a signal to the boiler about the information on or off the burner."
I'm not convinced though. You can try to just buy the OT2 and see if it works, if it doesn't purchase the OT1 as well.

**Comment by cagnulein** [comment]
@adorobis i'm not convinced me neither 😄 
The OT2 has in its kit the OT1 so it's not a problem.
My thought is that i can set the OT1 to high value in order to keep the 111-W always on, with the same behaviour that i have now.
But, adding the OT2, i can turn on/off and set the temperature of the hotwater and floor. What do you think?

**Comment by adorobis** [comment]
Probabably you are right. I have an older system with room control Vitotroll 300 and OPTO1 Vitoconnect device. Regardless if I use the remote control via vitoconnect or not the room sensor turns entire heating off if it reaches the set temperature. So in order to have heating on in rooms which are slower to heat up I need to increase the set room temperature exactly as you propose. But having the Vitoconnect I can still benefit from remote controls of entire system.

**Comment by cagnulein** [comment]
i just bought the OT2 and OT1. I will tell you if it will work in a week or two. Thanks in advance

**Comment by ge0van** [comment]
@cagnulein:
Hello. So, was the OT1 installation mandatory or not? I want to do the same with my boiler.

**Comment by cagnulein** [comment]
Yes it is

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 8 apr 2021 alle ore 16:26 ge0van ***@***.***>
ha scritto:

**Comment by ge0van** [comment]
Ok. Thanks!
