### ISSUE TITLE
Unable to read .getCurrentPower()

### ISSUE THREAD

**Issue by bzc0fq** [openviess/PyViCare#48]
Hi,

Could you please help me and advice on how to properly declare a device in order to read Current Power?

What I tried was:
from PyViCare.PyViCareDevice import Device
from PyViCare.PyViCareGazBoiler import GazBoiler

t=GazBoiler('xxxxx@email.com','xxxxxx','/tmp/vicare_token.save',0,10)

t1=t.getCurrentPower()
print('T1=', t1)

And... what I get is:
'error'

I tried a few parameters with GasBoiler init but it did not help.

Any suggestions please?

Thanks!

**Comment by somm15** [comment]
Did you try other funtions that getCurrentPower? 
For instance, it does not work at my place. I have an error as well just because my boiler does not support it.

**Comment by crazyfx1** [comment]
Power is not available anymore in V2.
