### ISSUE TITLE
Split the PyViSession object

### ISSUE THREAD

**Issue by somm15** [openviess/PyViCare#5]
@oischinger If you don't mind, I would split PyViCare in the following way:

The main object would be "ViCareGateway".
It creates a "VicareSession" and passes it to its members self.installation[0]=Installation(ViCareGateway,0)

.getInstallation(id=0) --> return an Installation object
.getInstallation().getWaterHeater()--> returns a WaterHeater object
.getInstallation().getBoiler() --> returns a Boiler object
.getInstallation().getMeter() --> returns a Meter object (all the consumptions functions)

As you have the only project embedding the app so far, any comments?
I think it better maps the actual setup.

**Comment by somm15** [comment]
And by the way, version 0.0.21 with your functions is now on Pypi

**Comment by oischinger** [comment]
@somm15
I don't mind any breaking changes at that time ;). I guess it's a good idea to split it up.

**Comment by somm15** [comment]
Solved
