### ISSUE TITLE
Change error in case of value not found

### ISSUE THREAD

**Issue by somm15** [openviess/PyViCare#52]
@crazyfx1 and @oischinger 
As far as I know, you are the 2 main users and contributors. 

I change the error returned in PyVicareDevice from just "error" to 
except KeyError as err:
        	return "KeyError: "+str(err)

1) Is it a problem for the ha integration?

So it's already a little bit better. However, it's still far from clean. Error or not both return a string. 
I would prefer to raise a custom made error.
(or just stop stop catching the error and pass it, but I guess it would be more flexible to catch it and make an error custom made to have a message more clear). 

2) I guess small changes would be required in the HA integration to catch the error.

**Comment by crazyfx1** [comment]
Yes this would indeed be an issue. The HA component checks if the return value is "error" and reacts accordingly.

I think it would be better to create and throw a custom exception (like PyViCareException) with the error text. Then the HA component needs to adapt and catch the exception.

**Comment by oischinger** [comment]
I agree.
Actually custom exceptions is also what HA code style recommends for error handling.
