### ISSUE TITLE
Add additional tests and sample responses

### ISSUE THREAD

**Issue by woehrl01** [openviess/PyViCare#59]
As we now have unit tests (see #55), it would be awesome to collect additional responses for the individual devices, to ensure correct behavior. 

* [x] Gaz (thx @cagnulein)
* [x] FuelCell (@nbraem ?)
* [x] OilBoiler (@o00batman00o ?)
* [x] HeatPump (@crazyfx1 ?)

Please ensure to scramble your DeviceId, GatewaySerial and InstallationId. 

Adding the file to the `test` directory in the format `response_[devicename].json` would be sufficient, the tests can be added later on.

What do you think?

**Comment by jborup** [comment]
Added one more gazboiler in PR #130

**Comment by cagnulein** [comment]
hello guys, with the new API i can't read anymore the burner hours from my vitoconnect OT2 and Viessman 111W. is it supposed to work? Everything was fine with API v.1.x

Fixed in #177

**Comment by woehrl01** [comment]
@cagnulein Yes, it should work, I saw that you provided a fix, so that the auto-detection works for your device. Thanks!
