### ISSUE TITLE
push a new version to pypi

### ISSUE THREAD

**Issue by nbraem** [openviess/PyViCare#67]
I would like to use the added PyViCareFuelCell in the vicare integration for Home Assistant, but the current version 0.2.4 does not include it yet. Would it be possible to push a new version to pypi?

**Comment by somm15** [comment]
It is finally done.
Not yet with the workflow, but done.
Sorry for the delay.

**Comment by oischinger** [comment]
Thanks alot. Home Assistant PR is on the way: https://github.com/home-assistant/core/pull/45301

**Comment by adorobis** [comment]
Great! Does it also include the vicare_mode service?

**Comment by oischinger** [comment]
This one is already merged

**Comment by adorobis** [comment]
Thanks! I have missed that so now I can remove the custom component :)

**Comment by adorobis** [comment]
Hmm, I've removed the custom component but the vicare_mode service is not there. I have the latest updates for HA. Should I configure anything more to enable this service? I can see that vicare components do have the required functions in the climate.py module.

**Comment by oischinger** [comment]
It's merged but the new HA version is not yet released. Sorry for the confusion

**Comment by woehrl01** [comment]
@somm15 I'm currently extending HA and would like to use the newly added method `getDomesticHotWaterChargingActive` (PR #70). Would be awesome if you could release version 0.2.6 with that included. Thanks!
