### ISSUE TITLE
dhw vs heating circuits

### ISSUE THREAD

**Issue by ddokupil** [openviess/PyViCare#73]
A few thing or maybe hacks I would need:
- can I enable or disable dhw pump off the schedule / on demand?
- I can disable both circuits by setting it to standby but that also cuts off dhw heating. How can I set them to dhw only mode?
BTW, despite of what is in a comment standby mode works, at least in my case.

**Comment by woehrl01** [comment]
Hi @ddokupil I just added this feature in #124 .

To set it to dhw only, you can send "dhw" via `setMode`.
