### ISSUE TITLE
Switch to Viessmann (authorization) V2 API

### ISSUE THREAD

**Issue by TheJulianJES** [openviess/PyViCare#74]
It looks like Viessmann has opened their Developer Portal and has released a new API (at least for authorization):

Original post: https://community.home-assistant.io/t/viessmann-component/77873/343

> Viessmann Developer Portal:
> As some of you have probably seen as well, Viessmann has now opened access to testing of the long time ago announced Viessmann Developer Portal. In the communication I have received they are suggesting making some changes in our already existing integrations:
> We also have two specific advices we would like you to consider already in your current implementations:
> 
> For authorization, switch to the v2 endpoint: https://iam.viessmann.com/idp/v2/authorize
> The v1 endpoint is deprecated and will be deactivated soon, so make sure not to use this endpoint anymore for any implementations.
> Blockquote
> > You can retrieve all accessible features with one single API request. To do this, use the following endpoint:
> > Device features: https://api.viessmann.com/iot/v1/equipment/installations/{installationId}/gateways/{gatewaySerial}/devices/{deviceId}/features
> > Installation features: https://api.viessmann.com/iot/v1/equipment/installations/{installationId}/features
> > This saves you a API requests.
> 
> Is anybody looking into it already?

(Perhaps by condensing some of the API requests, multiple circuit support in Home Assistant could be done easier: https://community.home-assistant.io/t/viessmann-multiple-circuits/153223)

**Comment by crazyfx1** [comment]
Maybe thats the point we take the take time to refactor the whole service like @somm15  suggested in other issues.
