### ISSUE TITLE
F-strings require python 3.6

### ISSUE THREAD

**Issue by jackie-t** [openviess/PyViCare#76]
As stated in the title, f-strings require python 3.6, thus no longer supporting installations with python 3.4.
So, after pip3 install -upgrade, you go from 0.2.4 to 0.2.5 and your installation is hosed.

`Traceback (most recent call last):
  File "./viessmann_status.py", line 3, in <module>
    from PyViCare.PyViCareDevice import Device
  File "/usr/local/lib/python3.4/dist-packages/PyViCare/PyViCareDevice.py", line 6, in <module>
    from PyViCare.PyViCareService import ViCareService
  File "/usr/local/lib/python3.4/dist-packages/PyViCare/PyViCareService.py", line 35
    return f'{apiURLBase}/operational-data/v1/installations/{id}/gateways/{serial}/devices/0/features/{property_name}/{action}'
`

and that's just for mere two lines. 

Changing those back to:

```
def buildSetPropertyUrl(id, serial, property_name, action):
    return ('{apiURLBase}/operational-data/v1/installations/{id}/gateways/{serial}/devices/0/features/{property_name}/{action}').format(apiURLBase=apiURLBase, id=id, serial=serial, property_name=property_name, action=action)

def buildGetPropertyUrl(id, serial, property_name):
    return ('{apiURLBase}/operational-data/v1/installations/{id}/gateways/{serial}/devices/0/features/{property_name}/').format(apiURLBase=apiURLBase, id=id, serial=serial, property_name=property_name)

```

immediately fixes the problem.

I'd be nice to either make it clear that going from 0.2.4 to 0.2.5 does that, or decide that it's not worth removing support over two single string-building lines.

I mean, if there's tons of python 3.6 stuff, sure, but two lines ...?

**Comment by woehrl01** [comment]
Close as we now require python 3.6 due to other dependencies
