### ISSUE TITLE
Possibility to read/set dhw circulation

### ISSUE THREAD

**Issue by AnduriI** [openviess/PyViCare#79]
Hey everyone,

is the above mentioned function working? I have setup PyViCare a few months ago, but this parameter shows 'True' all the time. My circulation is configured to be active only 5am-10pm.
By the way, is there also a way to influence the circulationpump? I would like to activate it only if someone is at home (respectively deactivate when no one is in the house).
I use a Viessmann heatpump Vitocal 200-S with Vitoconnect (in case that matters). The other readings (e.g. temperature, compressor,...) are fine.

Regards,
Anduril

**Comment by oischinger** [comment]
Hi, for me it is working because it goes to off when in dhw mode for some minutes. during night it doesn't go to off for me because I when it's off in the schedule it the heater is in reduced mode and not off

**Comment by AnduriI** [comment]
For me checking the status of the circulation pump always returns True (with `print(t.getCirculationPumpActive())`)
. Only when I set my dht to off it reports back false.
Is it intended to be true while the circulation is enabled (5/10 or 5/25 setting in the vitotronic) or only when it is running, so only the 5min and not the 25 when idling (or 10, depending on setting)?

**Comment by crazyfx1** [comment]
I think the confusion comes from the translation to english.
The circulation pump here is the internal pump which delivers the water to the radiators or underfloor heating pipes (="Umwälzpumpe").
The "circulation" you mean (which cycles water in the warm water system) is not implemented. Someone would need to provide a ViCare result which includes the data, since I don't have that circulation installed.

**Comment by oischinger** [comment]
I have circulation installed but it's not controlled by the Viessmann heater (instead the circulation pump has it's own sensor going to the hot water storage which triggers pump turn on/off). Actually I am not sure if the Viessmann device has the capability to control a circulation pump of that kind.

**Comment by crazyfx1** [comment]
The Vitotronic 200 can control warm water circulation pumps.

**Comment by AnduriI** [comment]
I have a Vitotronic 200 and it is controlling both, the heating of my water storage and the circulation in my piping controlled by it.The mandatory circulation pump for radiators/underfloor heating is of course also there, but I thought that it is running all the time when heating mode is enabled. Otherwise the Vitotronic wouldn't be able to detect when additional heat is needed.
I thought for the water storage heating there is the function getDomesticHotWaterChargingActive(), but that didn't yielded usefull results either.
@crazyfx1 in case I can provide this data to you, just tell me how and I will do my best to help

**Comment by AnduriI** [comment]
With the changes to the new api I had a look at this again. I found that the response for a Vitocall 200 includes that datapoint stated in the api docs "heating.circuits.N.dhw.pumps.circulation.schedule" 

https://github.com/somm15/PyViCare/blob/16269aa2959a39414e9468fd8a7038edc4e4a707/tests/response_Vitocal200.json#L1284

and

https://github.com/somm15/PyViCare/blob/16269aa2959a39414e9468fd8a7038edc4e4a707/tests/response_Vitocal200.json#L2079


Shouldn't it be possible to use this to read the state and even set the dhw-circulation to 5/10, 5/25 or off?

**Comment by adorobis** [comment]
I have also doubts to what those sensors are actually showing. When you look at what I have for my system (obviously during summer only DHW mode is used):
![image](https://user-images.githubusercontent.com/19752098/126481854-97d8703b-48ff-4a94-b731-0f1df1fe5c65.png)
So looks like pumps and chargingactive are fully aligned with burner on. Is it exactly this way in reality I don't know, would need to observe what the vito controller shows.

**Comment by AnduriI** [comment]
Well I think the internal circulation pump is intended to work that way: when you add heat to the system (by turning on burner/heatpump/...) it should activate to spread the heat in underfloorheating/...
Maybe I should change the title to account for dhw.circulation, because that's what I want to view/set.

**Comment by adorobis** [comment]
OK, got it. This feature is not implemented yet, testing it now in my system.

**Comment by adorobis** [comment]
Looks that it works for me, I've created a PR https://github.com/somm15/PyViCare/pull/114 with this change

**Comment by adorobis** [comment]
@AnduriI The status of dhw circulation pump is implemented now. There is no possibility to control it (turn on/off) in the API so I would close this issue now.

**Comment by AnduriI** [comment]
Thank you very much for this feature. That is great.
I see that there is no simply way to switch on/off, but couldn't we parse a json string to dhw.pumps.circulation.schedule to either run all day or deactivate it the complete day?

**Comment by adorobis** [comment]
It would be a kind of bodge / workaround. Wouldn't it be better to switch the heater to standby or forcedReduced modes? Both would result in turning the dhw circulation pump off.

**Comment by AnduriI** [comment]
I fully agree with you. That would not be a full feature but more of a hack. I don't now about the modes you mentioned, are they documented somewhere?
As far as I can see in the docs and the response there is no good option for switching the dhw circulation on/off. Therefor thank you very much again for implementing the status feature.
If those modes will not work I will still try to 'hack' that feature for my personal use...

**Comment by adorobis** [comment]
Vitocall 200 supports the following modes, looking at the features response:
https://github.com/somm15/PyViCare/blob/16269aa2959a39414e9468fd8a7038edc4e4a707/tests/response_Vitocal200.json#L294

```
                "active",
                "cooling",
                "dhw",
                "dhwAndHeating",
                "dhwAndHeatingCooling",
                "heating",
                "heatingCooling",
                "normalStandby",
                "standby"
```
Look at this, you'll be able to get possible modes and set them using getModes() and setMode()
https://github.com/somm15/PyViCare/blob/25a012bc926083dd719cf99b10b3a47ad20ea184/PyViCare/PyViCareDevice.py#L63

**Comment by AnduriI** [comment]
The getModes does not list all of them, but only standby, dhw and dhwAndHeatingCooling. None of them leaves me with heating and dhw working but dhw circulation deactivated.
getProgram gives a list a little longer, but I don't know the meaning of all of them: ['active', 'comfort', 'eco', 'fixed', 'normal', 'reduced', 'standby']
I know about normal and reduced, as they are used by schedule. I think eco and comfort are also self explaining, but for the others I have no idea if one of them fulfils my needs.

**Comment by AnduriI** [comment]
@woehrl01 Thanks for adding this feature. But how to actually use it? I tried `t.getDomesticHotWaterCirculationSchedule()` but it only gave the response `['5/25-cycles', '5/10-cycles', 'on']` (so only the options, not my specific schedule).
What to enter as a valid argument for `setDomesticHotWAterCirculationSchedule("")`? Do I simply add 5/25, 5/10 or on and this is used till the next command (either via API or schedule)?

**Comment by woehrl01** [comment]
@AnduriI I haven't used this on my device yet to be honest.

**Comment by woehrl01** [comment]
I just added additional methods which return the current active mode.
