### ISSUE TITLE
Retrieval of each property as an individual request is forcing an rate limit exception

### ISSUE THREAD

**Issue by williwacker** [openviess/PyViCare#84]
I have made an adoption to your version that does only a single request and retrieves all available properties. From this you can then extract the individual values. For debugging purposes you can cache the data into a file and always read from this file as long as it exists.

**Comment by crazyfx1** [comment]
This is already implemented. 
If you pass the cacheDuration in the constructor of your PyViCareDevice, the internal service is changed to a cached service. This service will cache the result for the duration. I recommend 60 seconds, which is exactly the Viessmann limit.
