### ISSUE TITLE
important API authentication changes as of 15th of July

### ISSUE THREAD

**Issue by BrechtMo** [openviess/PyViCare#86]
I'm not sure this will impact the PyViCare libarary but I'm afraid so.

---

Dear Developer,
 

An evaluation has shown that you have used the web interface (API) to Viessmann IoT Services to access data from the Viessmann backend through a 3rd party application. We wanted to let you know that we now have a Developer Portal you can use for this purpose. 
 

The Developer Portal offers great benefits for both Developers and End-users:
 

    Easy to create an account and generate a new API key
    Continued access to heating system data for development of new applications
    Full documentation around our API to help you get started
    First-level support to answer any queries you may have
    And more to come!

 

## Important Changes
 

In order to keep our API stable into the future, we must therefore shut down access to any old API keys that were not obtained through the Viessmann Developer Portal. **On July 15th, 2021 access to old API keys will no longer be possible**.
 

## What must you do?
 

If you are using an old API client, which you have not created through the Developer Portal and you are a:
 

## Developer

    Check your plugin to assure that it is working with the authorization flow, described here: https://developer.viessmann.com/en/doc/authentication. Every user will need their own API key to access their device. This means sharing one API key will not be possible anymore and users will need to have their own API key for continued access to data.
    Some data points that were accessible through the old API client will not be accessible through the new API client. Make sure to check the list of features provided in the documentation: https://developer.viessmann.com/de/doc/iot

 

## End-user

If you are using a 3rd party application to connect to your heating device, you need to go on the Developer Portal to create your own API key. This will be your personal key, which you need to access your device.
 

You can also find the information on the changes in our Change Log, where we will add relevant questions and answers.
 

If you are unsure if this affects you, first check whether your personal Viessmann account is used to access the web interface. If you are still unsure, feel free to reach us at developer@viessmann.com
 

We are pleased there has been so much demand for use of our API. We want to invite you to continue to develop your applications, so please carefully follow the instructions included here.
 

In the meantime, if you have any questions, feel free to contact us developer@viessmann.com
 

All the best
 

Your Viessmann Developer Portal Team

**Comment by cagnulein** [comment]
yeah i was thinking the same while i was reading the email :(

**Comment by BrechtMo** [comment]
some good news: I was missing some features (solar boiler temperatures) on the new api but they seem to have been added.

**Comment by jackie-t** [comment]
I'm pretty certain this does impact PyViCare, and actions are needed, otherwise it'll cease to function in one month.

At least the API is well documented, the sample cURL calls work fine, and I'm able to access the API using nothing but the command line and cURL.

**Comment by crazyfx1** [comment]
I tried the API aswell and it works. But unfortunately there are many properties missing for heatpumps. For example heating rod data and statistics (starts, hours, the V1 even added the power consumption in the end).

**Comment by mawiak** [comment]
Would pyvicare get a update?

**Comment by crazyfx1** [comment]
Yes, we need to update PyViCare to work with the new API. But every user will need to register in the developer portal to get a (free) API key.

**Comment by crazyfx1** [comment]
The update is in #88 . As soon as the code is merged we need users to test their heating systems and report back for missing properties. Ideally those users should send an email to the viessmann developer support and ask them to add the missing properties.

**Comment by AnduriI** [comment]
Is there already an update been pushed to PyPi? I installed PyViCare via pip and (obviously) need to use the new V2API...
Is there another way to update this manually?

**Comment by BrechtMo** [comment]
the old API access seems to have stopped around 15:30 today. 
It will indeed be necessary for the new PyViCare to be available in official package indexes so that environments like Home Assistant will use the new libraries.

In the meantime you can build and install the latest build from github using 
```
python setup.py build
pip install .
```
I'm no python expert at all so all input is appreciated.

**Comment by woehrl01** [comment]
As the version 1.x with the new auth flow has been published and the HA integration has been merged. I'll close the issue.
