### ISSUE TITLE
Project maintenance and collaborators

### ISSUE THREAD

**Issue by somm15** [openviess/PyViCare#87]
Hello Guys, 

I don't really have enough time to maintain the project as it should be. In addition, I barely use it as I installed controlled valve actuator (much better, no cloud).
@oischinger @woehrl01 @crazyfx1 Who do I add as contributor?
(and for Pypi as well)

Regards,

Simon

**Comment by crazyfx1** [comment]
I would do it if one of the other gentlemen joins aswell. There are big changes coming to this library.

**Comment by oischinger** [comment]
I would love to spend more time on this but thanks to Corona impacts on family and job I just find no free time to do anything really productive.

Adding me as contributor would not really change the situation I'm afraid.

**Comment by woehrl01** [comment]
Hi @somm15 

thanks for asking to join as a contributor. Aktually I would be interested in doing so. Especially focusing on automating the release of new version would be a blast.

Let's take this responsibility together @crazyfx1

**Comment by hnykda** [comment]
I'm so grateful you are communicating your availability so clearly! @somm15 

And I'm even more grateful to you @woehrl01 and @crazyfx1 for taking over! My gas boiler is happy!

**Comment by crazyfx1** [comment]
Hi @somm15 . 
Can we get the permissions soon? Time is running out till the July, 15th :(

**Comment by somm15** [comment]
Sorry, done

**Comment by somm15** [comment]
@woehrl01 and @crazyfx1, can I please get your pip usernames?

**Comment by crazyfx1** [comment]
I've just registered, it's also crazyfx1, thanks!

**Comment by woehrl01** [comment]
It's woehrl01 for me too. Thanks @somm15

**Comment by somm15** [comment]
Done. Please make sure to enable 2FA on your account and use the test pypi before making packages for live.

**Comment by woehrl01** [comment]
Thanks @somm15 . Can you please assign me the "Maintain" role for the GitHub repo, so that I can configure the required secrets for GitHub Actions?
