### ISSUE TITLE
setMode sometimes results in 502 Bad Gateway

### ISSUE THREAD

**Issue by oischinger** [openviess/PyViCare#9]
When I change mode via t.setMode('forcedReduced') I often get the following answer:
{'error': 'Bad Gateway', 'statusCode': 502, 'message': 'DEVICE_COMMUNICATION_ERROR'}

If I didn't change modes after a long time it seems like the first mode-change works but after that another call to setMode causes the 502 error.

I never have any problem like this with activateProgram.

Obviously this is not a library problem but has anybody seen something similar as well?

**Comment by somm15** [comment]
Did you check, I think it's related to which mode you are transitioning from.
Should I throw an error when this occur?

**Comment by somm15** [comment]
It was event in the comments:
DEVICE_COMMUNICATION_ERROR can just mean that the program is already on

**Comment by oischinger** [comment]
You're right. that was exactly the case.
I wrote some code to avoid this situation.
