### ISSUE TITLE
Errors on all device features

### ISSUE THREAD

**Issue by prior-philip** [openviess/PyViCare#93]
Hey Team,
I see that great piece of software migrating to API V2.
Following the instructions using users personal token seems to work. At least I see a token generated, so I assume the authentication happens.
Although, any feature I request its status responds value "error" - even the most generic ones.
Unfortunately no error message appears or any other valuable information.

Anything I can do to provide relevant information?

**Comment by crazyfx1** [comment]
Thanks for testing out the V2 API.
Unfortunately the new API is only providing very basic info. Detailed info like statistics or usage are currently not available. 

Which type of heating system do you have?

**Comment by BrechtMo** [comment]
I'm experiencing the same. But my tests might be doing something wrong.

```
>>> print(t.getSupplyTemperature())
error
```

however querying the value does work
```
>>> t.service.getProperty("heating.boiler.sensors.temperature.commonSupply")
{'data': {'properties': {'unit': {'value': 'celsius', 'type': 'string'}, 'value': {'type': 'number', 'value': 41, 'unit': 'celsius'}, 'status': {'type': 'string', 'value': 'connected'}}, 'commands': {}, 'components': [], 'apiVersion': 1, 'uri': 'https://api.viessmann-platform.io/iot/v1/equipment/installations/XXX/gateways/XXX/devices/0/features/heating.boiler.sensors.temperature.commonSupply', 'gatewayId': 'XXX', 'feature': 'heating.boiler.sensors.temperature.commonSupply', 'timestamp': '2021-07-10T14:11:44.010Z', 'isEnabled': True, 'isReady': True, 'deviceId': '0'}}
```

**Comment by BrechtMo** [comment]
I think properties is now a member of "data" where properties used to be in the root of the return value.

So we need to do
`["data"]["properties"]["value"]["value"]`
instead of the old
`["properties"]["value"]["value"]`

**Comment by crazyfx1** [comment]
That should already work. You need to pass "useV2=True" to your device as described in the readme.

**Comment by BrechtMo** [comment]
I was doing that. I'm testing with Master.

```
>>> t=GazBoiler("XX@gmail.com","XX","token.save", client_id=client_id, useV2=True)
>>> t.getBurnerActive()
'error'
>>> t.service.getProperty("heating.burner")["data"]["properties"]["active"]["value"]
False
```

**Comment by crazyfx1** [comment]
Ok yes, the uncached service is broken. Please use the cached version by passing cacheDuration=60 to your device.

**Comment by prior-philip** [comment]
It seems this discussion brings up some unexpected behavior.
In order to reply to crazyfx1:
Tested with a Vitocal200S Heatpump - and I changed the test script accordingly.

For some reasons Im getting KeyError messages.
`ubuntu@colonia:~/Smarthome/Viessmann_API$ ./test_ViCareHeatPump.py
Traceback (most recent call last):
  File "/home/ubuntu/Smarthome/Viessmann_API/./test_ViCareHeatPump.py", line 12, in <module>
    t=HeatPump("myname@myprovider.com","mypassword","token.save", client_id=client_id, useV2=True)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 61, in __init__
    self.service = ViCareServiceV2(username, password, client_id, token_file, circuit)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareServiceV2.py", line 77, in __init__
    self._getInstallations()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareServiceV2.py", line 270, in _getInstallations
    self.id = self.installations["data"][0]["id"]
KeyError: 'data'
` 

Last time I tried it relied back "error". Did something change?

**Comment by prior-philip** [comment]
Okay, changed to cached service but behavior is same:
`
ubuntu@colonia:~/Smarthome/Viessmann_API$ ./test_ViCareHeatPump.py
Traceback (most recent call last):
  File "/home/ubuntu/Smarthome/Viessmann_API/./test_ViCareHeatPump.py", line 12, in <module>
    t=HeatPump("myusername@myprovide.com","mypasswd","token.save", client_id=client_id, cacheDuration=60, useV2=True)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareDevice.py", line 66, in __init__
    self.service = _ViCareCachedServiceV2_(username, password, cacheDuration, client_id, token_file, circuit)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareCachedServiceV2.py", line 8, in __init__
    ViCareServiceV2.__init__(self, username, password, client_id, token_file, circuit)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareServiceV2.py", line 77, in __init__
    self._getInstallations()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/PyViCare/PyViCareServiceV2.py", line 270, in _getInstallations
    self.id = self.installations["data"][0]["id"]
KeyError: 'data'
`

**Comment by crazyfx1** [comment]
Please try to delete the token-file "token.save" in your directory and try again.

**Comment by prior-philip** [comment]
> Please try to delete the token-file "token.save" in your directory and try again.
Yepp.... That was the trick! (y)

Nevertheless. 
All features still reply error. Thru Postman its okay.

**Comment by BrechtMo** [comment]
I don't see in the code how the cacheDuration and useV2 parameters change how the functions extract the values from the api return values for the features.

The old 
["properties"]["value"]["value"] 
doesn't work anymore.

**["data"]**["properties"]["value"]["value"] 
does work.

As far as I can see this is causing all features to return `error`.

**Comment by crazyfx1** [comment]
The implementation of the service is changed when passing those parameters.
https://github.com/somm15/PyViCare/blob/2bc0fd5a9f3d0ed732257547d7eb41b346f27341/PyViCare/PyViCareDevice.py#L66

If both are set, the ViCareCachedServiceV2 is used. This service implements getProperty by using the "data" property of the result.

https://github.com/somm15/PyViCare/blob/2bc0fd5a9f3d0ed732257547d7eb41b346f27341/PyViCare/PyViCareCachedServiceV2.py#L17

**Comment by prior-philip** [comment]
> The implementation of the service is changed when passing those parameters.
> https://github.com/somm15/PyViCare/blob/2bc0fd5a9f3d0ed732257547d7eb41b346f27341/PyViCare/PyViCareDevice.py#L66
> 
> If both are set, the ViCareCachedServiceV2 is used. This service implements getProperty by using the "data" property of the result.
> 
> https://github.com/somm15/PyViCare/blob/2bc0fd5a9f3d0ed732257547d7eb41b346f27341/PyViCare/PyViCareCachedServiceV2.py#L17

All right.
In PyViCareDevice.py the parameter order is:
username, password, cacheDuration, client_id, tokenfile, circuit

Do I have to reorder it in the device parameters as well?

**Comment by prior-philip** [comment]
Yepp. Thats now working for me....
Thanks man.

**Comment by crazyfx1** [comment]
The uncached service should work aswell now. But I don't recommend it since you only have 1450 requests per day ;)
